Repository scinote-eln/scinote-web, pull requests merged in 2018-04, with the labels that each got.

#1071 Fix repository rows permissions [SCI-2265]
  app/controllers/repository_rows_controller.rb
  app/permissions/team.rb
Labels: master

#1067 Style Guide - refactor colors, typography and buttons [SCI-2243]
  app/assets/javascripts/projects/index.js.erb
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/extend/bootstrap.scss
  app/assets/stylesheets/my_modules.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/partials/_tree_view.scss
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/protocol_management.scss
  app/assets/stylesheets/reports.scss
  app/assets/stylesheets/sample_types_groups.scss
  app/assets/stylesheets/search.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/themes/buttons.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/menu_bar.scss
  app/assets/stylesheets/themes/scinote.scss
  app/javascript/src/components/Navigation/components/GlobalActivitiesModal.jsx
  app/javascript/src/components/data_grid/index.jsx
  app/javascript/src/components/data_table/index.jsx
  app/javascript/src/config/constants/colors.js
  app/javascript/src/styles/constants.scss
  app/javascript/src/styles/main.scss
  app/views/my_modules/_state_button_uncomplete.html.erb
  app/views/my_modules/results.html.erb
  app/views/protocols/_steps.html.erb
  app/views/user_notifications/index.html.erb
  app/views/users/registrations/edit.html.erb
  config/initializers/constants.rb
Labels: ux release 1 :nail_care:

#1065 refactor smart annotation parser, adds repository item to smart annot…
  app/helpers/application_helper.rb
  app/permissions/project.rb
  app/services/smart_annotations/permision_eval.rb
  app/services/smart_annotations/preview.rb
  app/services/smart_annotations/tag_to_html.rb
  spec/services/smart_annotations/permission_eval_spec.rb
  spec/services/smart_annotations/preview_spec.rb
  spec/services/smart_annotations/tag_to_html_spec.rb
Labels: ux release 1 :nail_care:

#1047 adds libraries/repositories to sidebar navigation and blank page for no libraries/repositories
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/repositories/show.js
  app/assets/javascripts/sidebar_toggle.js.erb
  app/assets/stylesheets/themes/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/repositories_controller.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/index.html.erb
  app/views/repositories/show.html.erb
  app/views/shared/_left_menu_bar.html.erb
  app/views/shared/_sidebar.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/routes.rb
Labels: ux release 1 :nail_care:

#1073 add ID column to repository [fixes SCI-2206]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/helpers/repository_datatable_helper.rb
  app/models/concerns/searchable_model.rb
  app/models/my_module.rb
  app/services/repository_datatable_service.rb
  app/services/repository_zip_export.rb
  app/views/repositories/_repository_row_info_modal.html.erb
  app/views/repositories/_repository_table.html.erb
  app/views/search/results/_repositories.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  spec/controllers/repository_rows_controller_spec.rb
  spec/services/repository_datatable_service_spec.rb
  spec/support/api/schemas/repository_row_datatables.json
Labels: ux release 1 :nail_care:

#1072 change export model wording [fixes SCI-2239]
  app/views/repositories/_export_repository_modal.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1075 Remove remotipart from Gemfile.lock
  Gemfile.lock
Labels: master

#1076 fix merge bananas
  app/views/repositories/show.html.erb
Labels: ux release 1 :nail_care:

#1078 Fix Office Online (WOPI) editing of files [SCI-2266]
  Gemfile
  Gemfile.lock
  app/middlewares/wopi_method_override.rb
  config/application.rb
Labels: master

#1079 fixes smart annotation avatar bug in pdf reports[fixes SCI-2282]
  app/views/reports/report.pdf.erb
Labels: master

#1077 fixes tiny_mce pdf report in filesystem storage mode [fixes SCI-2279]
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/reports_helper.rb
  app/helpers/tiny_mce_helper.rb
  app/views/reports/elements/_my_module_result_text_element.html.erb
  app/views/reports/elements/_my_module_step_element.html.erb
Labels: master

#1049 adds manage columns page
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/javascripts/repository_columns/index.js.erb
  app/assets/stylesheets/themes/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/repository_columns_controller.rb
  app/helpers/repository_columns_helper.rb
  app/views/repositories/show.html.erb
  app/views/repository_columns/_delete_column_modal.html.erb
  app/views/repository_columns/_delete_column_modal_body.html.erb
  app/views/repository_columns/_manage_column_modal.html.erb
  app/views/repository_columns/index.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/routes.rb
Labels: ux release 1 :nail_care:

#1080 add asset field preview/sort/search in repository table [fixes SCI-2076]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/helpers/repository_datatable_helper.rb
  app/services/repository_datatable_service.rb
  app/views/repositories/_asset_link.html.erb
Labels: ux release 1 :nail_care:

#1084 fixes bug with CSRF on file upload, fixes turbolink issues with remot…
  app/assets/javascripts/my_modules/results.js.erb
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/samples/samples.js
  app/assets/javascripts/sitewide/form_errors.js
  app/middlewares/wopi_method_override.rb
  app/views/repositories/_import_repository_records_modal.html.erb
  app/views/result_assets/_edit.html.erb
  app/views/samples/_import_samples_modal.html.erb
  config/routes.rb
Labels: master

#1085 adds asset preview link to repository row modal and to table row item…
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/javascripts/sitewide/repository_row_info_modal.js
  app/helpers/repository_datatable_helper.rb
  app/views/layouts/application.html.erb
  app/views/my_modules/_result_user_generated.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/results.html.erb
  app/views/protocols/edit.html.erb
  app/views/protocols/index.html.erb
  app/views/repositories/_asset_link.html.erb
  app/views/repositories/_repository_row_info_modal.html.erb
  app/views/shared/_asset_link.html.erb
  app/views/steps/_form_assets.html.erb
  app/views/steps/_step.html.erb
Labels: ux release 1 :nail_care:

#930 Remove tutorial [SCI-1860]
  Gemfile
  Gemfile.lock
  Makefile
  app/assets/demo_files/6dpi_height.JPG
  app/assets/demo_files/96plate.doc
  app/assets/demo_files/Bioanalyser_result.JPG
  app/assets/demo_files/BootCamp-Experiment-results-20122.sds
  app/assets/demo_files/DSCN0354.JPG
  app/assets/demo_files/DSCN0660.JPG
  app/assets/demo_files/G2938-90034_KitRNA6000Nano_ebook.pdf
  app/assets/demo_files/Mixes_Templats.xls
  app/assets/demo_files/RNeasy-Plant-Mini-Kit-EN.pdf
  app/assets/demo_files/curves.JPG
  app/assets/demo_files/cycling_conditions.JPG
  app/assets/demo_files/ddCq-quantification_diagnostics-results.xls
  app/assets/demo_files/ddCq-quantification_diagnostics-template.xls
  app/assets/demo_files/dilution_curve-efficiency.JPG
  app/assets/demo_files/reaction_setup.JPG
  app/assets/demo_files/result-ddCq.JPG
  app/assets/demo_files/sample-potatoe.txt
  app/assets/demo_files/sample_preparation.JPG
  app/assets/demo_files/samples.txt
  app/assets/demo_files/tables_content.yaml
  app/assets/demo_files/totRNA_gel.jpg
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/my_modules/protocols.js.erb
  app/assets/javascripts/my_modules/results.js.erb
  app/assets/javascripts/projects/canvas.js.erb
  app/assets/javascripts/projects/index.js.erb
  app/assets/javascripts/projects/show.js
  app/assets/javascripts/protocols/index.js
  app/assets/javascripts/reports/index.js
  app/assets/javascripts/reports/new.js.erb
  app/assets/javascripts/samples/samples.js
  app/assets/javascripts/sitewide/utils.js
  app/assets/javascripts/users/settings/account/preferences/index.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/application_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/users/settings/account/preferences_controller.rb
  app/models/user.rb
  app/utilities/delayed_uploader_demo.rb
  app/utilities/first_time_data_generator.rb
  app/views/my_modules/protocols.html.erb
  app/views/users/settings/account/preferences/_repeat_tutorial_modal_body.html.erb
  app/views/users/settings/account/preferences/index.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20180109102914_remove_tutorial_status_from_user.rb
  spec/models/user_spec.rb
Labels: ux release 1 :nail_care:

#1087 rename Repository/Library => Inventory [fixes SCI-2240]
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1089 remove unneeded label in destroy repository record modal [fixes SCI-2…
  app/views/repositories/_delete_record_modal.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1090 fixes edin/destory button on repository page after redirected from co…
  app/views/repository_columns/index.html.erb
Labels: ux release 1 :nail_care:

#1092 adds edit repository item permission to normal user [fixes SCI-2297]
  app/helpers/repository_datatable_helper.rb
  app/views/repositories/show.html.erb
Labels: ux release 1 :nail_care:

#1093 hides the create new inventory button for non admin users [fixes SCI-…
  app/controllers/repositories_controller.rb
  app/views/repositories/index.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1095 fixes archive button [fixes SCI-2300]
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/projects_controller.rb
Labels: ux release 1 :nail_care:

#1096 Change links in help [SCI-2125]
  app/assets/stylesheets/themes/menu_bar.scss
  config/initializers/constants.rb
Labels: ux release 1 :nail_care:

#1097 Change JS compressor from :uglifier to Uglifier.new(harmony: true)
  config/environments/production.rb
Labels: ux release 1 :nail_care:

#1091 adds correct preview images to files [fixes SCI-2254]
  app/helpers/file_icons_helper.rb
  app/views/my_modules/archive.html.erb
  app/views/my_modules/archive/_result.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1098 Fix project navigation to work with archived pages and… [SCI-2306]
  app/controllers/experiments_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/projects_controller.rb
  app/views/projects/archive.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/shared/sidebar/_projects.html.erb
Labels: ux release 1 :nail_care:

#1102 Fix screen responsiveness [SCI-2308]
  app/assets/stylesheets/themes/main_navigation.scss
Labels: ux release 1 :nail_care:

#1104 Fix blocked buttons edit and eye icon [SCI-2312]
  app/views/shared/_left_menu_bar.html.erb
Labels: ux release 1 :nail_care:

#1103 Fix top navigation style [SCI-2309]
  app/assets/stylesheets/themes/main_navigation.scss
Labels: ux release 1 :nail_care:

#1099 Remove breadcrumbs throughout application [SCI-2167]
  app/assets/javascripts/sidebar_toggle.js.erb
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/secondary_navigation_helper.rb
  app/views/protocols/_breadcrumbs.html.erb
  app/views/protocols/edit.html.erb
  app/views/protocols/index.html.erb
  app/views/repositories/_breadcrumbs.html.erb
  app/views/shared/_secondary_navigation.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1086 enables copying of repository items [fixes SCI-2207]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/repository_rows_controller.rb
  app/services/repository_actions/duplicate_cell.rb
  app/services/repository_actions/duplicate_rows.rb
  app/views/repositories/_repository_table.html.erb
  app/views/repositories/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/repository_rows_controller_spec.rb
  spec/services/repository_actions/duplicate_rows_spec.rb
Labels: ux release 1 :nail_care:

#1083 set limit on maximum number of dropdown list items [fixes SCI-2259]
  app/assets/javascripts/repository_columns/index.js.erb
  app/controllers/repository_columns_controller.rb
  app/utilities/repository_import_parser/importer.rb
  app/utilities/repository_import_parser/list_items_column.rb
  app/utilities/repository_import_parser/repository_cell_value_resolver.rb
  app/views/repositories/_parse_records_modal.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  spec/models/repository_list_item_spec.rb
  spec/utilities/repository_import_parser/repository_cell_value_resolver_spec.rb
Labels: ux release 1 :nail_care:

#1105 change repository icon
  app/services/smart_annotations/preview.rb
  spec/services/smart_annotations/preview_spec.rb
Labels: ux release 1 :nail_care:

#1107 Fix file preview background [SCI-2314]
  app/assets/stylesheets/themes/scinote.scss
Labels: ux release 1 :nail_care:

#1100 Update reports show page to work with new navigation [SCI-2303]
  app/assets/javascripts/reports/new.js.erb
  app/assets/stylesheets/reports.scss
  app/controllers/reports_controller.rb
  app/views/reports/new.html.erb
  app/views/reports/new/_report_navigation.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1109 add permission to column management [fixes SCI-2297]
  app/views/repositories/show.html.erb
Labels: ux release 1 :nail_care:

#1108 fix file preview [SCI-2313]
  app/views/shared/_asset_link.html.erb
Labels: ux release 1 :nail_care:

#1101 adds new reports index page [fixes SCI-2124]
  app/assets/javascripts/reports/index.js
  app/assets/javascripts/reports/reports_datatable.js.erb
  app/assets/stylesheets/themes/repositories.scss
  app/controllers/reports_controller.rb
  app/datatables/report_datatable.rb
  app/models/project.rb
  app/models/report.rb
  app/models/team.rb
  app/models/user_project.rb
  app/models/user_team.rb
  app/models/views/datatables/datatables_report.rb
  app/permissions/project.rb
  app/permissions/team.rb
  app/views/reports/index.html.erb
  app/views/reports/new/_report_navigation.html.erb
  app/views/shared/_left_menu_bar.html.erb
  app/views/shared/_secondary_navigation.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20180416114040_add_team_id_to_reports.rb
  db/migrate/20180417062042_create_datatables_reports.rb
  db/schema.rb
  db/views/datatables_reports_v01.sql
  spec/factories/reports.rb
  spec/models/report_spec.rb
  spec/models/team_spec.rb
  spec/models/views/datatables/datatables_report_spec.rb
Labels: :bangbang: migration :bangbang:, ux release 1 :nail_care:

#1113 rename smart annotations icons [fixes SCI-2307]
  app/services/smart_annotations/preview.rb
  spec/services/smart_annotations/preview_spec.rb
  spec/services/smart_annotations/tag_to_html_spec.rb
Labels: ux release 1 :nail_care:

#1111 Update the code for repository table states so it (hopefully) causes less errors [SCI-2276]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/repository_columns_controller.rb
  app/controllers/user_repositories_controller.rb
  app/helpers/repository_datatable_helper.rb
  app/models/repository_column.rb
  app/models/repository_table_state.rb
  app/services/repository_datatable_service.rb
  app/services/repository_table_state_column_update_service.rb
  app/services/repository_table_state_service.rb
  app/utilities/hash_util.rb
  app/views/repository_columns/_delete_column_modal_body.html.erb
  config/initializers/constants.rb
  config/initializers/helpers_in_assets.rb
Labels: ux release 1 :nail_care:

#1117 remove task description info from canvas task card [fixes SCI-2187]
  app/assets/javascripts/projects/canvas.js.erb
  app/views/canvas/_full_zoom.html.erb
  app/views/canvas/full_zoom/_my_module.html.erb
Labels: ux release 1 :nail_care:

#1114 removes samples from views [fixes SCI-2304]
  app/controllers/search_controller.rb
  app/views/canvas/full_zoom/_my_module.html.erb
  app/views/experiments/samples.html.erb
  app/views/my_modules/samples.html.erb
  app/views/projects/samples.html.erb
  app/views/reports/new/modal/_module_contents_inner.html.erb
  app/views/search/index.html.erb
  app/views/search/results/partials/_my_module_text.html.erb
  app/views/shared/_secondary_navigation.html.erb
  config/initializers/assets.rb
  config/initializers/extends/report_extends.rb
  config/routes.rb
  spec/controllers/api/v20170715/core_api_controller_spec.rb
Labels: ux release 1 :nail_care:
