Repository scinote-eln/scinote-web, pull requests merged in 2018-05, with the labels that each got.

#1122 repository when sorting/searching bug fix [SCI-2339]
  app/models/concerns/searchable_model.rb
  app/services/repository_datatable_service.rb
Labels: ux release 1 :nail_care:

#1118 sign_out user after 7 days [fixes SCI-2323]
  app/models/user.rb
  config/initializers/devise.rb
  spec/factories/users.rb
Labels: ux release 1 :nail_care:

#1119 fixes flash message [fixes SCI-2142]
  app/assets/javascripts/application.js.erb
  app/assets/stylesheets/themes/scinote.scss
  app/views/layouts/application.html.erb
  app/views/layouts/fluid.html.erb
  app/views/shared/_flash_alerts.html.erb
Labels: ux release 1 :nail_care:

#1124 fix the missing icons on task card [fixes SCI-2347]
  app/assets/stylesheets/themes/scinote.scss
Labels: ux release 1 :nail_care:

#1126 adds new string truncation method [fixes SCI-2344]
  app/controllers/reports_controller.rb
  app/helpers/string_utility.rb
  config/initializers/constants.rb
Labels: ux release 1 :nail_care:

#1112 propagate assigned repository items in workflow [fixes SCI-2261]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/my_modules_controller.rb
  app/models/repository_row.rb
  app/views/my_modules/modals/_assign_repository_records_modal.html.erb
  app/views/my_modules/modals/_unassign_repository_records_modal.html.erb
  app/views/my_modules/repository.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: ux release 1 :nail_care:

#1131 Re-init file preview modal after column visability change [SCI-2379]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: ux release 1 :nail_care:

#1132 Move REPOSITORIES_LIMIT from constants to env variables [SCI-2301]
  app/controllers/at_who_controller.rb
  app/controllers/repositories_controller.rb
  app/permissions/team.rb
  config/initializers/constants.rb
  config/initializers/repositories.rb
Labels: ux release 1 :nail_care:

#1129 Fix merge conflict introduced in when merging master->ux-release-1
  app/assets/javascripts/repositories/index.js
Labels: ux release 1 :nail_care:

#1133 fixes error message for invalid file type [fixes SCI-2337]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: ux release 1 :nail_care:

#1135 Fix editing of inventory rows with existing files [SCI-2394]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/repository_rows_controller.rb
Labels: ux release 1 :nail_care:

#1138 Disable some validations in repository import to improve speed [SCI-2404]
  Gemfile.lock
  app/models/repository_cell.rb
  app/utilities/repository_import_parser/importer.rb
Labels: ux release 1 :nail_care:

#1139 Fix task resore permissions [SCI-2385]
  app/controllers/my_modules_controller.rb
Labels: ux release 1 :nail_care:

#1140 Re-init file preview modal after inventory row editing [SCI-2391]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: ux release 1 :nail_care:

#1137 UI/UX restyle - fixes throughout application - part 2 [SCI-2336]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/projects/canvas.js.erb
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/reports.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/canvas/_edit.html.erb
  app/views/canvas/edit/_my_module.html.erb
  app/views/my_module_comments/_comment.html.erb
  app/views/project_comments/_comment.html.erb
  app/views/projects/index/_project.html.erb
  app/views/repositories/show.html.erb
  app/views/result_comments/_comment.html.erb
  app/views/shared/_navigation.html.erb
  app/views/shared/_secondary_navigation.html.erb
  app/views/step_comments/_comment.html.erb
  app/views/users/settings/teams/_user_dropdown.html.erb
  app/views/users/settings/teams/new.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1141 Add clear file selector button to repository edit [SCI-2403]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/themes/repositories.scss
Labels: ux release 1 :nail_care:

#1147 fixes ajax error in repositories [fixes SCI-2399]
  app/helpers/application_helper.rb
Labels: ux release 1 :nail_care:

#1146 Add locales [SCI-2336]
  app/assets/javascripts/my_modules/protocols.js.erb
  app/assets/javascripts/protocols/index.js
  app/assets/javascripts/reports/reports_datatable.js.erb
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/javascripts/users/settings/teams/show.js
  app/assets/stylesheets/themes/scinote.scss
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1128 adds deface hook in support dropdown [fixes SCI-2331]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/javascripts/samples/sample_datatable.js.erb
  app/views/shared/_left_menu_bar.html.erb
  vendor/assets/javascripts/dataTables.noSearchHidden.js
Labels: ux release 1 :nail_care:

#1148 UI/UX restyle - update colours for navigation [SCI-2343]
  app/assets/javascripts/sidebar.js.erb
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/partials/_tree_view.scss
  app/assets/stylesheets/themes/menu_bar.scss
  app/views/repositories/_sidebar.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_projects.html.erb
  app/views/users/settings/_sidebar.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1152 Change remove file button appearence [SCI-2403]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/themes/repositories.scss
Labels: ux release 1 :nail_care:

#1151 shorten project name [fixes SCI-2344]
  app/controllers/reports_controller.rb
Labels: ux release 1 :nail_care:

#1150 migrations that fixes the bug with smart annotations [fixes SCI-2426]
  app/models/repository.rb
  db/migrate/20180518113526_remove_repository_rows_and_columns_without_repository.rb
  db/schema.rb
Labels: ux release 1 :nail_care:

#1153 Final button colour changes [SCI-2440]
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/users/settings/account/preferences/index.js
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/protocol_management.scss
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/bootstrap_form_helper.rb
  app/views/my_modules/_state_button_complete.html.erb
  app/views/my_modules/protocols/_copy_to_repository_modal_body.html.erb
  app/views/steps/_step.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1155 Update new repository row code so file columns work again [SCI-2436]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/repository_rows_controller.rb
Labels: ux release 1 :nail_care:

#1157 Init selectpicker for move workflow to another experiment modal [SCI-2432]
  app/assets/javascripts/projects/canvas.js.erb
Labels: ux release 1 :nail_care:

#1162 fix toggle button on inventory page [SCI-2440]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/views/my_modules/repository.html.erb
Labels: ux release 1 :nail_care:

#1161 move the open/close arrow to the bottom of left menu [SCI-2350]
  app/assets/stylesheets/themes/scinote.scss
  app/views/shared/_left_menu_bar.html.erb
Labels: ux release 1 :nail_care:

#1158 Update software with new logo & new brand [SCI-2416]
  LICENSE.txt
  README.md
  app/javascript/src/components/Navigation/index.jsx
  app/javascript/src/components/data_grid/index.jsx
  app/javascript/src/config/locales/messages.js
  app/javascript/src/scenes/SettingsPage/scenes/preferences/components/NotificationsGroup.jsx
  app/middlewares/wopi_method_override.rb
  app/utilities/users_generator.rb
  config/application.rb
  config/initializers/addon_loader.rb
  config/initializers/constants.rb
  config/initializers/load_addons_specs.rb
  config/locales/en.yml
  config/secrets.yml
  docs/dev_documentation.md
  features/home_page.feature.pending
  features/invite_user.feature.pending
  features/navigation/addons_versions_modal.feature.pending
  features/project.feature.pending
  features/sessions/forgot_password.feature
  features/sessions/log_in.feature
  features/sessions/sign_up.feature
  lib/generators/addon/USAGE
  lib/generators/addon/templates/README.md
  lib/tasks/protocol_keyword_team.rake
  lib/tasks/versions/generate_release_name.rake
  package.json
  public/images/logo.png
  test/mailers/previews/app_mailer_preview.rb
Labels: ux release 1 :nail_care:

#1163 Fix bug with protocol preview does not open… [SCI-2425]
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
Labels: ux release 1 :nail_care:

#1154 fix access to public reports [fixes SCI-2340]
  app/controllers/reports_controller.rb
  app/models/project.rb
  app/models/views/datatables/datatables_report.rb
  spec/models/views/datatables/datatables_report_spec.rb
Labels: ux release 1 :nail_care:

#1159 adds data-hook in save_PDF_to_inventory modal [fixes SCI-2372]
  app/views/reports/new/_save_PDF_to_inventory_modal.html.erb
Labels: ux release 1 :nail_care:

#1167 Fix search in repositories [SCI-2428]
  app/controllers/search_controller.rb
Labels: ux release 1 :nail_care:

#1169 Delete _report_sidebar.html.erb
  app/views/reports/new/_report_sidebar.html.erb
Labels: ux release 1 :nail_care:

#1171 Change login button color to green
  app/views/users/sessions/new.html.erb
Labels: ux release 1 :nail_care:

#1170 adds flash_message div in manage repository column page
  app/assets/javascripts/repository_columns/index.js.erb
  app/views/layouts/application.html.erb
  app/views/repository_columns/index.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1173 fixes sidebar animation [fixes SCI-2451]
  app/assets/javascripts/sidebar_toggle.js.erb
Labels: ux release 1 :nail_care:

#1172 fix error if user is not assigned to any teams [SCI-2405]
  app/views/layouts/application.html.erb
  app/views/projects/index.html.erb
  app/views/protocols/index.html.erb
  app/views/repositories/index.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1174 Fix left menu word breaking [SCI-2458]
  app/assets/stylesheets/themes/menu_bar.scss
Labels: ux release 1 :nail_care:

#1166 Fix WOPI controller to support repositories [SCI-2342]
  app/controllers/wopi_controller.rb
Labels: ux release 1 :nail_care:

#1165 fixes tast description/due-date modal [fixes SCI-2433]
  app/controllers/my_modules_controller.rb
Labels: ux release 1 :nail_care:

#1164 adds discard gem, move deletion of repositories in a rake task to run…
  Gemfile
  Gemfile.lock
  app/controllers/repositories_controller.rb
  app/jobs/clear_discarded_repositories_job.rb
  app/models/repository.rb
  app/services/smart_annotations/html_preview.rb
  app/services/smart_annotations/permision_eval.rb
  db/migrate/20180518113526_remove_repository_rows_and_columns_without_repository.rb
  db/migrate/20180524091143_add_discard_to_repositories.rb
  db/schema.rb
  lib/tasks/clear_repository_rows_and_columns_without_repository.rake
  spec/services/smart_annotations/html_preview_spec.rb
Labels: :bangbang: migration :bangbang:, ux release 1 :nail_care:

#1176 fixes items assign flash message [fixes SCI-2395]
  app/controllers/my_modules_controller.rb
  config/locales/en.yml
Labels: master

#1177 fixes bug with empty submit of repository row [fixes SCI-2420]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: master

#1180 Fix align bullet with a file name [SCI-2390]
  app/assets/stylesheets/steps.scss
Labels: master

#1182 Fix position of navigation bar is not saved [SCI-2459]
  app/assets/javascripts/sidebar_toggle.js.erb
Labels: master

#1183 fixes sidebar [fixes SCI-2451]
  app/assets/javascripts/sidebar_toggle.js.erb
Labels: master

#1181 Fix inventory rows without files not being saved bug [SCI-2471]
  app/models/asset.rb
Labels: master
