Repository scinote-eln/scinote-web, pull requests merged in 2018-11, with the labels that each got.

#1342 Update styling of Sign up page [SCI-2764]
  app/assets/stylesheets/themes/scinote.scss
  app/views/users/registrations/new.html.erb
  app/views/users/registrations/new_with_provider.html.erb
  app/views/users/shared/_links.html.erb
  config/locales/en.yml
Labels: master

#1357 Fix permission helpers in delayed export job [SCI-2834]
  Dockerfile
  Dockerfile.production
  Gemfile
  app/models/project.rb
Labels: features/export-all

#1359 Fix bug with new project button not working [SCI-2843]
  app/assets/javascripts/projects/index.js
  app/views/projects/index.html.erb
Labels: features/export-all

#1360 Fix empty projects page bug and projects tree bug [SCI-2837]
  app/assets/javascripts/projects/index.js
  app/controllers/projects_controller.rb
  app/models/user.rb
  app/views/projects/index.html.erb
Labels: features/export-all

#1361 Improve counters on projects overview table [SCI-2785]
  app/services/projects_overview_service.rb
Labels: features/export-all

#1341 Improve error messages in API [SCI-2773]
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/connections_controller.rb
  app/controllers/api/v1/experiments_controller.rb
  app/controllers/api/v1/inventories_controller.rb
  app/controllers/api/v1/inventory_cells_controller.rb
  app/controllers/api/v1/inventory_columns_controller.rb
  app/controllers/api/v1/inventory_items_controller.rb
  app/controllers/api/v1/inventory_list_items_controller.rb
  app/controllers/api/v1/project_comments_controller.rb
  app/controllers/api/v1/projects_controller.rb
  app/controllers/api/v1/protocols_controller.rb
  app/controllers/api/v1/reports_controller.rb
  app/controllers/api/v1/results_controller.rb
  app/controllers/api/v1/task_groups_controller.rb
  app/controllers/api/v1/task_inventory_items_controller.rb
  app/controllers/api/v1/task_tags_controller.rb
  app/controllers/api/v1/task_users_controller.rb
  app/controllers/api/v1/tasks_controller.rb
  app/controllers/api/v1/teams_controller.rb
  app/controllers/api/v1/user_identities_controller.rb
  app/controllers/api/v1/user_projects_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/serializers/api/v1/project_serializer.rb
  config/initializers/rack_attack.rb
  config/locales/en.yml
  spec/requests/api/v1/experiments_controller_spec.rb
  spec/requests/api/v1/inventories_controller_spec.rb
  spec/requests/api/v1/inventory_cells_controller_spec.rb
  spec/requests/api/v1/inventory_columns_controller_spec.rb
  spec/requests/api/v1/inventory_items_controller_spec.rb
  spec/requests/api/v1/inventory_list_items_controller_spec.rb
  spec/requests/api/v1/projects_controller_spec.rb
  spec/requests/api/v1/results_controller_spec.rb
  spec/requests/api/v1/tasks_controller_spec.rb
  spec/requests/api/v1/teams_controller_spec.rb
  spec/requests/api/v1/user_identities_controller_spec.rb
  spec/requests/api/v1/users_controller_spec.rb
Labels: core-api

#1363 Fix user_project manage permission [SCI-2795]
  app/controllers/user_projects_controller.rb
Labels: master

#1365 Fix user counters on projects overview page [SCI-2847]
  app/services/projects_overview_service.rb
Labels: features/export-all

#1366 Improve Export All button behaviour [SCI-2839]
  app/assets/javascripts/projects/index.js
  app/views/projects/index.html.erb
Labels: features/export-all

#1358 Removal of the temporary files for export all [SCI-2646]
  app/models/team_zip_export.rb
  app/models/zip_export.rb
  app/services/repository_zip_export.rb
  spec/services/repository_zip_export_spec.rb
Labels: features/export-all

#1371 Fix visual bug (everything bold) on projects index page
  app/views/projects/index.html.erb
Labels: master

#1370 Allow automatic redirection to the O365 sign-in page in the business user flow [SCI-2853]
  app/views/assets/edit.erb
  app/views/assets/view.erb
Labels: master

#1364 Add time format selection to settings [SCI-2778]
  app/controllers/activities_controller.rb
  app/controllers/application_controller.rb
  app/controllers/my_module_comments_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/project_comments_controller.rb
  app/controllers/result_comments_controller.rb
  app/controllers/step_comments_controller.rb
  app/controllers/users/settings/account/preferences_controller.rb
  app/datatables/custom_datatable.rb
  app/datatables/load_from_repository_protocols_datatable.rb
  app/datatables/protocols_datatable.rb
  app/datatables/team_users_datatable.rb
  app/helpers/application_helper.rb
  app/helpers/bootstrap_form_helper.rb
  app/models/user.rb
  app/models/zip_export.rb
  app/services/custom_i18n_backend.rb
  app/views/my_module_comments/_list.html.erb
  app/views/project_comments/_list.html.erb
  app/views/projects/show/_experiment.html.erb
  app/views/result_comments/_list.html.erb
  app/views/step_comments/_list.html.erb
  app/views/users/settings/account/preferences/index.html.erb
  config/initializers/constants.rb
  config/initializers/i18n.rb
  config/locales/en.yml
Labels: master

#1374 Update the Export all confirmation modal and export interaction [SCI-2842]
  app/assets/javascripts/projects/index.js
  app/controllers/teams_controller.rb
  app/views/projects/export/_error.html.erb
  app/views/projects/export/_modal.html.erb
  app/views/projects/export/_success.html.erb
  app/views/projects/index.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: master

#1367 Add unit tests for status/health API endpoints
  spec/controllers/api/api_controller_spec.rb
Labels: core-api

#1369 Refactor result and step comments [SCI-2830]
  app/assets/javascripts/comments.js.erb
  app/assets/javascripts/projects/canvas.js.erb
  app/controllers/result_comments_controller.rb
  app/controllers/step_comments_controller.rb
  app/models/asset.rb
  app/models/checklist.rb
  app/models/result.rb
  app/models/result_asset.rb
  app/models/result_comment.rb
  app/models/result_table.rb
  app/models/result_text.rb
  app/models/step_asset.rb
  app/models/step_comment.rb
  app/models/step_table.rb
  app/models/table.rb
  app/models/tiny_mce_asset.rb
  app/models/user_my_module.rb
  app/models/user_team.rb
  app/views/comments/_edit.html.erb
  app/views/my_modules/_result.html.erb
  app/views/my_modules/results.html.erb
  app/views/protocols/_steps.html.erb
  app/views/result_comments/_comment.html.erb
  app/views/result_comments/_index.html.erb
  app/views/step_comments/_comment.html.erb
  app/views/step_comments/_index.html.erb
  app/views/steps/_step.html.erb
Labels: master

#1377 Fix DataTable display for protocol modal [SCI-2863]
  app/assets/javascripts/protocols/index.js
Labels: master

#1378 All users in smart annotation have removed in brackets [SCI-2861]
  app/views/my_module_comments/_comment.html.erb
  app/views/my_modules/_description_label.html.erb
  app/views/project_comments/_comment.html.erb
  app/views/projects/experiment_archive/_experiment.html.erb
  app/views/projects/show/_experiment.html.erb
  app/views/result_comments/_comment.html.erb
  app/views/results/_result_text.html.erb
  app/views/step_comments/_comment.html.erb
  app/views/steps/_step.html.erb
Labels: master

#1362 Export - various small changes/fixes [SCI-2817]
  app/models/team_zip_export.rb
  app/models/zip_export.rb
  app/views/reports/elements/_experiment_element.html.erb
  app/views/reports/elements/_my_module_element.html.erb
  app/views/reports/elements/_project_header_element.html.erb
Labels: master

#1384 Fix teams switch not working at navigating from task [SCI-2846]
  app/views/shared/_navigation.html.erb
Labels: master

#1385 Fix in app help window does not close in some cases [SCI-2866]
  app/assets/javascripts/sitewide/tooltip_helper.js
Labels: master

#1389 Remove byebug from HTML template [SCI-2883]
  app/views/project_comments/_comment.html.erb
Labels: master

#1394 Update export email's look & feel [SCI-2884]
  app/views/user_notifications/_list.html.erb
  app/views/user_notifications/_recent_notifications.html.erb
  app/views/users/mailer/notification.html.erb
  config/locales/en.yml
  test/mailers/previews/app_mailer_preview.rb
Labels: master

#1393 Protocols - import from protocols.io doesn't work
  app/controllers/protocols_controller.rb
  app/helpers/protocols_io_helper.rb
  app/views/protocols/import_export/_import_json_protocol_p_desc.html.erb
  app/views/protocols/import_export/_import_json_protocol_preview_modal.html.erb
  app/views/protocols/import_export/_import_json_protocol_s_desc.html.erb
  app/views/protocols/protocolsio_import_create.js.erb
  config/locales/en.yml
Labels: master

#1396 Fix handsontable initialization [SCI-2882]
  app/assets/javascripts/protocols/steps.js.erb
  app/views/my_modules/results.html.erb
  app/views/protocols/_steps.html.erb
  app/views/protocols/index.html.erb
  app/views/reports/new.html.erb
  app/views/search/results/_protocols.html.erb
Labels: master

#1392 Hide sign-in with third party applications (e.g. LinkedIn) in Oauth… [SCI-2676]
  app/controllers/users/sessions_controller.rb
  app/views/users/shared/_links.html.erb
  config/initializers/devise.rb
Labels: master

#1397 Fix support menu for Safari [SCI-2885]
  app/assets/stylesheets/themes/menu_bar.scss
Labels: master

#1399 Add subfolder option to S3 bucket config [SCI-2727]
  config/initializers/paperclip.rb
Labels: master

#1400 Make AWS access key variables optional [SCI-2727]
  config/initializers/aws.rb
  config/initializers/paperclip.rb
Labels: master

#1402 Add bottom margin to OAuth authorize page, for better mobile xp
  app/assets/stylesheets/themes/scinote.scss
Labels: master
