Repository scinote-eln/scinote-web, pull requests merged in 2018-09, with the labels that each got.

#1285 Replaced image icon with paperclip on scinote [SCI-2712]
  app/views/my_modules/_result.html.erb
  app/views/my_modules/archive/_result.html.erb
  app/views/my_modules/results.html.erb
  app/views/search/results/_assets.html.erb
  app/views/search/results/_results.html.erb
Labels: master

#1275 Fixed table add and remove crash [SCI-2621]
  app/controllers/steps_controller.rb
Labels: master

#1294 add unit tests for Create inventory_column endpoint [SCI-2699]
  app/controllers/api/v1/inventory_columns_controller.rb
  spec/requests/api/v1/inventory_columns_controller_spec.rb
Labels: core-api

#1292 Created API endpoints for experiments and related data [SCI-2666]
  app/controllers/api/v1/connections_controller.rb
  app/controllers/api/v1/experiments_controller.rb
  app/controllers/api/v1/my_module_groups_controller.rb
  app/controllers/api/v1/my_modules_controller.rb
  app/serializers/api/v1/connection_serializer.rb
  app/serializers/api/v1/experiment_serializer.rb
  app/serializers/api/v1/my_module_group_serializer.rb
  app/serializers/api/v1/my_module_serializer.rb
  config/routes.rb
Labels: core-api

#1277 Fixed disabled export button after new inventory item save [SCI-2629]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: master

#1303 Merge release-1.14.4 into master
  Gemfile
  app/assets/javascripts/sitewide/tiny_mce.js.erb
Labels: master

#1268 Add OAuth2 provider [SCI-2515]
  Gemfile
  Gemfile.lock
  app/controllers/api/api_controller.rb
  app/models/user.rb
  app/services/api/core_jwt.rb
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  config/application.rb
  config/initializers/api.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  db/migrate/20180813120338_create_doorkeeper_tables.rb
  db/schema.rb
  spec/controllers/api/api_controller_spec.rb
Labels: core-api

#1309 Merge release-1.14.5 into master
  VERSION
  app/controllers/search_controller.rb
  app/models/asset.rb
  app/models/repository.rb
Labels: master

#1287 Fixed blue block in dropdown, now its a full line [SCI-2672]
  app/assets/stylesheets/themes/scinote.scss
Labels: master

#1299 Update rubocop to 0.59.0, fix the config to be compliant
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: master

#1301 Fix CREATE inventory endpoint [SCI-2693]
  app/controllers/api/v1/inventories_controller.rb
Labels: core-api, priority

#1296 close mc-SC-2701; DELETE inventory column endpoint unit tests [SCI-2701]
  spec/requests/api/v1/inventory_columns_controller_spec.rb
Labels: core-api, priority

#1311 Improve delayed jobs for TempFile deletion and Asset text extraction [SCI-2738]
  app/controllers/teams_controller.rb
  app/models/asset.rb
  app/models/temp_file.rb
  app/services/import_repository/parse_repository.rb
Labels: master

#1286 ( better solution ) Search page results from different teams than active not switching active team on click [SCI-2684]
  app/controllers/experiments_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/protocols_controller.rb
  app/helpers/search_helper.rb
Labels: master

#1231 Tables sum error (tables now use big.js for +-/* calculations) [SCI-2587]
  vendor/assets/javascripts/ruleJS.js
Labels: master

#1302 Add CREATE Result endpoint: Create Text result [SCI-2718]
  app/controllers/api/v1/results_controller.rb
  app/serializers/api/v1/result_asset_serializer.rb
  app/serializers/api/v1/result_serializer.rb
  app/serializers/api/v1/result_table_serializer.rb
  app/serializers/api/v1/result_text_serializer.rb
  config/routes.rb
Labels: core-api, priority

#1289 Fixed bug with table name of step not being length validated [SCI-2719]
  app/assets/javascripts/protocols/steps.js.erb
Labels: master
