Repository scinote-eln/scinote-web, pull requests merged in 2018-03, with the labels that each got.

#996 generate custom repository when user is created [fixes SCI-2020]
  app/utilities/first_time_data_generator.rb
Labels: samples migration

#1010 Sign up with linkedIn account [SCI-1826]
  Gemfile
  Gemfile.lock
  app/assets/images/linkedin/Sign-in-Small---Active.png
  app/assets/images/linkedin/Sign-in-Small---Default.png
  app/assets/images/linkedin/Sign-in-Small---Hover.png
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  app/views/users/registrations/new_with_provider.html.erb
  app/views/users/shared/_links.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/initializers/extends.rb
  config/initializers/paperclip.rb
  config/locales/en.yml
  config/routes.rb
  lib/tasks/data.rake
Labels: master

#1000 Fixed big crash that was caused by invalid or null step hash in protocol [SCI-2043]
  app/controllers/protocols_controller.rb
  app/helpers/protocols_io_helper.rb
  app/views/protocols/import_export/_import_json_protocol_preview_modal.html.erb
  app/views/protocols/import_export/_import_json_protocol_s_desc.html.erb
Labels: master

#1003 Table missing scrollbar [SCI-1818]
  app/helpers/protocols_io_helper.rb
Labels: master

#1018 Fix sample's custom column permissions [SCI-2135]
  app/permissions/team.rb
Labels: master

#1019 Remove extra permission checks from WOPI buttons [SCI-2134][SCI-2133]
  app/helpers/wopi_helper.rb
Labels: master

#1016 Fix edit project's users modal [SCI-2130]
  app/views/projects/index.html.erb
Labels: master

#1021 Fix notification for user removal from a team [SCI-2131]
  app/controllers/users/settings/user_teams_controller.rb
Labels: master

#1022 Fix manage repository permissions [SCI-2136]
  app/permissions/team.rb
  app/views/repositories/_repository.html.erb
Labels: master

#1023 Refactor search to support repository list items [SCI-2108]
  app/controllers/search_controller.rb
  app/models/repository.rb
  app/models/repository_cell.rb
  app/models/repository_row.rb
  config/initializers/extends.rb
  db/migrate/20180207095200_create_repository_list_values.rb
Labels: samples migration

#1025 Fix user management on project [SCI-2146]
  app/controllers/user_projects_controller.rb
  app/views/user_projects/_index_edit_footer.html.erb
Labels: master

#1026 Add uniqueness validation for SamplesTable [SCI-2148][SCI-2149]
  app/controllers/user_samples_controller.rb
  app/models/samples_table.rb
Labels: master

#1024 Fix sample record creation [SCI-2145]
  app/controllers/samples_controller.rb
Labels: master

#1027 Hide delete button for guest users in repository [SCI-2163]
  app/permissions/team.rb
  app/views/repositories/_repository.html.erb
Labels: master

#998 migration script for migrating samples -> custom repositories [SCI-2014]
  app/services/tasks/samples_to_repository_migration_service.rb
  lib/tasks/samples_to_repository_migration.rake
  spec/factories/sample_custom_field.rb
  spec/lib/tasks/samples_to_repository_migration_spec.rb
  spec/services/tasks/samples_to_repository_migration_service_spec.rb
  spec/support/shared_contexts/rake.rb
Labels: samples migration

#1031 update bootstrap to v 3.3.7 [fixes SCI-2140]
  Gemfile
  Gemfile.lock
Labels: samples migration

#1028 Add file custom column type to db [SCI-2144]
  app/controllers/assets_controller.rb
  app/models/asset.rb
  app/models/repository_asset_value.rb
  app/models/repository_cell.rb
  config/initializers/extends.rb
  db/migrate/20180308094354_create_repository_asset_values.rb
  db/schema.rb
  spec/factories/repository_asset_values.rb
  spec/models/asset_spec.rb
  spec/models/repository_asset_value_spec.rb
Labels: samples migration

#1035 Fix repository export to support file columns [SCI-2079]
  app/controllers/repositories_controller.rb
  app/models/repository_asset_value.rb
Labels: samples migration

#1036 Implement importable selector for repository columns [SCI-2078]
  app/models/repository.rb
  app/models/repository_column.rb
  app/services/import_repository/parse_repository.rb
  config/initializers/extends.rb
Labels: samples migration

#1032 refactor global activities in separate page [fixes SCI-2141]
  app/assets/javascripts/activities/index.js
  app/assets/javascripts/navigation.js
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/activities_controller.rb
  app/views/activities/_activity.html.erb
  app/views/activities/_index.html.erb
  app/views/activities/_list.html.erb
  app/views/activities/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_navigation.html.erb
  config/initializers/assets.rb
Labels: samples migration

#1014 Fix custom repositories export so it supports "list of values" custom column types [fixes SCI-2025]
  app/controllers/repositories_controller.rb
  app/models/repository_list_value.rb
  app/services/repository_zip_export.rb
  spec/factories/repository_text_value.rb
  spec/lib/tasks/samples_to_repository_migration_spec.rb
  spec/models/repository_list_value_spec.rb
  spec/rails_helper.rb
  spec/services/repository_zip_export_spec.rb
  spec/support/background_job.rb
Labels: samples migration

#1033 re-structure top navigation bar [fixes SCI-2116]
  app/assets/javascripts/navigation.js
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/extend/bootstrap.scss
  app/assets/stylesheets/themes/buttons.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/shared/_navigation.html.erb
  config/locales/en.yml
  features/navigation/addons_versions_modal.feature.pending
  features/sessions/log_in.feature
  features/settings_page/profile.feature
  features/support/env.rb
  public/images/scinote_icon.jpg
Labels: samples migration

#1037 Implement/update flash messages/alerts with regards to new navigation [fixes SCI-2142]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/sitewide/url_handling.js
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/layouts/application.html.erb
Labels: samples migration

#1041 adds permission check to archived project SCI-2194
  app/views/projects/archive/_project.html.erb
  app/views/projects/archive/_team_projects.html.erb
Labels: master

#1042 Use larger LinkedIn sign-in button [SCI-2201]
  app/assets/images/linkedin/Sign-in-Large---Active.png
  app/assets/images/linkedin/Sign-in-Large---Default.png
  app/assets/images/linkedin/Sign-in-Large---Hover.png
  app/assets/stylesheets/themes/scinote.scss
  app/views/users/shared/_links.html.erb
Labels: master

#1012 Fix custom repositories import so it supports "list of values" custom column types [fixes SCI-2024]
  app/models/repository.rb
  app/utilities/repository_import_parser/importer.rb
  app/utilities/repository_import_parser/repository_cell_value_resolver.rb
  spec/fixtures/files/export.csv
  spec/utilities/repository_import_parser/importer_spec.rb
  spec/utilities/repository_import_parser/repository_cell_value_resolver_spec.rb
Labels: samples migration

#1039 Improve connections between repository models [SCI-1697]
  app/models/my_module_repository_row.rb
  app/models/repository_cell.rb
Labels: samples migration

#1044 Remove Power Up button [SCI-2117]
  app/assets/stylesheets/themes/main_navigation.scss
  app/views/shared/_navigation.html.erb
  config/locales/en.yml
Labels: samples migration, ux release 1 :nail_care:

#1043 Rename record to item in repository row info modal [SCI-2193]
  config/locales/en.yml
Labels: samples migration, ux release 1 :nail_care:

#1017 Write server-side endpoints for custom repositories [SCI-2068]
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/application.scss
  app/controllers/my_modules_controller.rb
  app/controllers/repository_list_items_controller.rb
  app/controllers/repository_rows_controller.rb
  app/datatables/repository_datatable.rb
  app/helpers/repository_datatable_helper.rb
  app/models/repository_column.rb
  app/models/repository_table_state.rb
  app/services/repository_datatable_service.rb
  app/views/repositories/_repository_table.html.erb
  app/views/repository_rows/index.json.jbuilder
  config/initializers/constants.rb
  config/routes.rb
  spec/controllers/repository_list_items_controller_spec.rb
  spec/controllers/repository_rows_controller_spec.rb
  spec/models/asset_text_datum_spec.rb
  spec/models/repository_list_value_spec.rb
  spec/services/repository_datatable_service_spec.rb
  spec/support/api/schemas/repository_row_datatables.json
  vendor/assets/javascripts/ajax-bootstrap-select.min.js
  vendor/assets/stylesheets/ajax-bootstrap-select.min.css
Labels: samples migration, ux release 1 :nail_care:

#1038 Code left-side menu bar [SCI-2118]
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/menu_bar.scss
  app/helpers/left_menu_bar_helper.rb
  app/views/layouts/application.html.erb
  app/views/shared/_left_menu_bar.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1048 Refactor existing columns management to control only Column visibility and order [SCI-2220]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/views/my_modules/repository.html.erb
  app/views/repositories/_columns_reorder_dropdown.html.erb
  app/views/repositories/_repository.html.erb
  app/views/repositories/_repository_table.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1054 Re-implement About sciNote modal [SCI-2238]
  app/views/shared/_navigation.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1050 Refactor project navigation [SCI-2120]
  app/assets/javascripts/sidebar.js.erb
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/partials/_tree_view.scss
  app/controllers/experiments_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/projects_controller.rb
  app/views/projects/archive.html.erb
  app/views/projects/index.html.erb
  app/views/reports/new/_report_sidebar.html.erb
  app/views/shared/_left_menu_bar.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_my_modules.html.erb
  app/views/shared/sidebar/_projects.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:

#1045 fixes import protocol bug for guest user [fixes SCI-2197]
  app/controllers/protocols_controller.rb
  app/views/protocols/index.html.erb
Labels: master

#1057 Fix sample assign permissions [SCI-2249]
  app/controllers/my_modules_controller.rb
  app/permissions/experiment.rb
  app/views/shared/_samples.html.erb
Labels: master

#1055 Skip asset if file is missing in protocol export [SCI-2250]
  app/controllers/protocols_controller.rb
Labels: master

#1061 Disable turbolinks on tasks navigation [SCI-2251]
  app/views/shared/sidebar/_my_modules.html.erb
Labels: master

#1064 Fix Office Online editing of files [SCI-2264]
  app/controllers/wopi_controller.rb
Labels: master

#1062 Rescale Linkedin buttons [SCI-2201]
  app/assets/images/linkedin/Sign-in-Large---Active.png
  app/assets/images/linkedin/Sign-in-Large---Default.png
  app/assets/images/linkedin/Sign-in-Large---Hover.png
Labels: master

#1066 updated repository import modal html [fixes SCI-2235]
  app/views/repositories/_parse_records_modal.html.erb
  config/locales/en.yml
Labels: ux release 1 :nail_care:
