Repository scinote-eln/scinote-web, pull requests merged in 2019-07, with the labels that each got.

#1883 SCI-3648 Error at importing one protocol without steps
  app/services/protocol_importers/build_protocol_from_client_service.rb
  app/services/protocol_importers/search_protocols_service.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
Labels: features/protocolsio_integration

#1902 Merge 'release-1.16.6' into 'master'
  VERSION
  app/models/concerns/tiny_mce_images.rb
  app/models/tiny_mce_asset.rb
  spec/models/tiny_mce_asset_spec.rb
Labels: master

#1875 Remove unassign_user_from_project notification…[SCI-3618]
  app/controllers/user_projects_controller.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/settings/user_teams_controller.rb
  app/helpers/notifications_helper.rb
  app/services/client_api/invitations_service.rb
  app/services/client_api/user_team_service.rb
Labels: master

#1892 SCI-3650, SCI-3655 Fix empty file name, empty description when parsing tables
  app/utilities/protocol_importers/protocols_io/v3/step_components.rb
  app/utilities/protocol_importers/tables_builder.rb
  spec/fixtures/files/protocol_importers/normalized_single_protocol.json
  spec/fixtures/files/protocol_importers/protocols_io/v3/single_protocol.json
  spec/utilities/protocol_importers/protocol_intermediate_object_spec.rb
Labels: features/protocolsio_integration

#1910 Fix styling for StepComponents in step description [SCI-3656]
  app/utilities/protocol_importers/protocols_io/v3/step_components.rb
  app/utilities/protocol_importers/tables_builder.rb
  app/views/protocol_importers/templates/_command.html.erb
  app/views/protocol_importers/templates/_dataset.html.erb
  app/views/protocol_importers/templates/_details.html.erb
  app/views/protocol_importers/templates/_gotostep.html.erb
  app/views/protocol_importers/templates/_note.html.erb
  app/views/protocol_importers/templates/_reagent.html.erb
  app/views/protocol_importers/templates/_software.html.erb
  app/views/protocol_importers/templates/_warning.html.erb
  app/views/protocol_importers/templates/protocol_description.html.erb
  app/views/protocol_importers/templates/step_description.html.erb
  spec/fixtures/files/protocol_importers/normalized_single_protocol.json
  spec/fixtures/files/protocol_importers/protocols_io/v3/single_protocol.json
Labels: features/protocolsio_integration, master

#1898 Fixes visual bugs on protocols.io and home page [SCI-3634]
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/assets/stylesheets/protocol_management.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/protocols/index/_external_protocols_tab.html.erb
  app/views/shared/_navigation.html.erb
  config/initializers/constants.rb
Labels: features/protocolsio_integration

#1913 Log to console when error occur on ProtocolsImport actions [SCI-3657]
  app/services/protocol_importers/import_protocol_service.rb
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  config/locales/protocols/en.yml
Labels: features/protocolsio_integration, master

#1911 [SCI-3660] Protocols preview (main pane): All the links in the preview are relative
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/controllers/external_protocols_controller.rb
  spec/controllers/external_protocols_controller_spec.rb
Labels: features/protocolsio_integration, master

#1922 Fix for safari on external protocols tab [SCI-3693]
  app/assets/stylesheets/protocol_management.scss
Labels: features/protocolsio_integration, master, priority

#1921 Fix page redirect and add success flash msg after protocols.io import [SCI-3641]
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/external_protocols_controller.rb
  app/views/layouts/application.html.erb
  app/views/layouts/main.html.erb
  app/views/reports/new.html.erb
  app/views/repository_columns/index.html.erb
  config/locales/en.yml
Labels: features/protocolsio_integration, master

#1912 Protocols list preview - Show published_on instead of created_on [SCI-3659]
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  app/views/protocol_importers/_protocol_card.html.erb
  config/initializers/constants.rb
  spec/fixtures/files/protocol_importers/normalized_list.json
Labels: features/protocolsio_integration, master

#1933 [SCI-3670] Show protocols at external protocols tab
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/services/protocol_importers/search_protocols_service.rb
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  config/initializers/constants.rb
  spec/utilities/protocol_importers/protocols_io/v3/api_client_spec.rb
Labels: features/protocolsio_integration, master

#1932 Inventory sharing - data-model update, permissions update [SCI-3687]
  app/controllers/api/v1/inventory_cells_controller.rb
  app/controllers/api/v1/inventory_columns_controller.rb
  app/controllers/api/v1/inventory_items_controller.rb
  app/controllers/assets_controller.rb
  app/controllers/repository_columns_controller.rb
  app/controllers/repository_list_items_controller.rb
  app/controllers/repository_rows_controller.rb
  app/controllers/wopi_controller.rb
  app/helpers/repository_datatable_helper.rb
  app/models/repository.rb
  app/models/team.rb
  app/models/team_repository.rb
  app/permissions/repository.rb
  app/permissions/repository_column.rb
  app/permissions/team.rb
  app/services/report_actions/save_pdf_to_inventory_item.rb
  app/views/repositories/show.html.erb
  config/initializers/extends.rb
  db/migrate/20190711125513_create_team_repositories.rb
  db/schema.rb
  spec/factories/team_repositories.rb
  spec/models/repository_spec.rb
  spec/models/team_repository_spec.rb
  spec/models/team_spec.rb
  spec/permissions/repositroy_permissions_spec.rb
Labels: features/inventory-improvements

#1915 Add tests for StepComponents [SCI-3531]
  app/utilities/protocol_importers/protocols_io/v3/step_components.rb
  spec/utilities/protocol_importers/protocols_io/v3/step_components_spec.rb
Labels: features/protocolsio_integration, master

#1876 Refactor MarvinJS core over active storage [SCI-3624]
  app/assets/images/icon_small/marvinjs.svg
  app/assets/javascripts/my_modules/results.js.erb
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/javascripts/sitewide/marvinjs_editor.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/javascripts/sitewide/tiny_mce_file_upload_plugin.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/marvinjs.scss
  app/assets/stylesheets/my_modules/results/index.scss
  app/assets/stylesheets/steps.scss
  app/controllers/assets_controller.rb
  app/controllers/marvin_js_assets_controller.rb
  app/controllers/tiny_mce_assets_controller.rb
  app/helpers/my_modules_helper.rb
  app/models/asset.rb
  app/models/marvin_js_asset.rb
  app/models/step.rb
  app/models/team.rb
  app/models/tiny_mce_asset.rb
  app/services/marvin_js_service.rb
  app/views/assets/marvinjs/_create_marvin_sketch_button.html.erb
  app/views/assets/marvinjs/_marvin_sketch_card.html.erb
  app/views/assets/marvinjs/_marvin_sketch_card_placeholder.html.erb
  app/views/my_modules/results.html.erb
  app/views/shared/_marvinjs_modal.html.erb
  app/views/steps/_empty_step.html.erb
  app/views/steps/attachments/_list.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20190426185413_create_marvin_js_assets.rb
  db/migrate/20190427115413_add_name_to_marvin_js_assets.rb
  db/schema.rb
  spec/factories/marvin_js_assets.rb
Labels: features/marvinjs-integration

#1938 Shared inventories basic controller [SCI-3691]
  app/controllers/team_repositories_controller.rb
  app/models/team_repository.rb
  config/routes.rb
  db/migrate/20190715150326_add_unique_index_to_team_repositories.rb
  db/schema.rb
  spec/controllers/team_repositories_controller_spec.rb
  spec/models/team_repository_spec.rb
Labels: features/inventory-improvements

#1949 Fix for file annotating on Safari [SCI-3724]
  app/assets/javascripts/sitewide/file_preview.js
  app/controllers/assets_controller.rb
  config/routes.rb
Labels: master

#1940 Show shared inventories in left navigation and fix read repository… [SCI-3689]
  app/assets/stylesheets/partials/_tree_view.scss
  app/assets/stylesheets/repositories.scss
  app/controllers/assets_controller.rb
  app/controllers/at_who_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/repositories_controller.rb
  app/controllers/repository_columns_controller.rb
  app/controllers/repository_rows_controller.rb
  app/controllers/search_controller.rb
  app/controllers/user_repositories_controller.rb
  app/controllers/wopi_controller.rb
  app/helpers/repository_datatable_helper.rb
  app/models/repository.rb
  app/models/team.rb
  app/permissions/repository.rb
  app/permissions/team.rb
  app/services/smart_annotations/permission_eval.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
  app/views/search/results/partials/_asset_text.html.erb
  app/views/search/results/partials/_repository_row_text.html.erb
  app/views/search/results/partials/_repository_text.html.erb
  spec/permissions/repositroy_permissions_spec.rb
Labels: features/inventory-improvements

#1939 Add activity logging for sharing inventories [SCI-3692]
  app/controllers/team_repositories_controller.rb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  spec/controllers/team_repositories_controller_spec.rb
Labels: features/inventory-improvements

#1945 Fix showing errors [SCI-3708]
  app/assets/javascripts/protocols/external_protocols_tab.js
Labels: master

#1951 Update global search, so it will be able to search through shared… [SCI-3688]
  app/assets/stylesheets/partials/_tree_view.scss
  app/assets/stylesheets/shared/icons.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/controllers/search_controller.rb
  app/helpers/icons_helper.rb
  app/models/repository.rb
  app/views/repositories/_sidebar.html.erb
  app/views/search/index.html.erb
  spec/requests/api/v1/inventories_controller_spec.rb
Labels: features/inventory-improvements
