Repository scinote-eln/scinote-web, pull requests merged in 2019-05, with the labels that each got.

#1719 Visual fixes for edit/add step on protocol [SCI-3399]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/steps.scss
  app/views/my_modules/protocols.html.erb
  app/views/steps/_edit.html.erb
  app/views/steps/_new.html.erb
Labels: features/note-section

#1720 One project is duplicated in project list [SCI-3375]
  app/models/project.rb
Labels: master

#1722 Fix tags line up [SCI-3406]
  app/assets/stylesheets/my_modules/protocols/index.scss
Labels: features/note-section

#1723 Fix issue with TInyMCE image upload plugin [SCI-3408]
  app/assets/javascripts/sitewide/tiny_mce_file_upload_plugin.js
Labels: features/note-section

#1726 Fix button icon for uncomplete task [SCI-3409]
  app/views/my_modules/_state_button_uncomplete.html.erb
Labels: features/note-section

#1725 Fix due date position [SCI-3411]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/views/my_modules/_module_header.html.erb
Labels: features/note-section

#1727 Fix bug when saving empty step description [SCI-3384]
  app/assets/javascripts/protocols/steps.js.erb
Labels: features/note-section

#1728 Update team exporter for new tinyMCE images [SCI-3262]
  app/models/tiny_mce_asset.rb
  app/services/team_importer.rb
Labels: features/note-section

#1730 Add task tag on enter button [SCI-3410]
  app/assets/javascripts/select2_customization.js
Labels: features/note-section

#1731 Fix floating tool bar and scroll issue after leaving editor [SCI-3418]
  app/assets/javascripts/sitewide/tiny_mce.js
Labels: features/note-section

#1732 Clear step edit textarea status before going to edit mode [SCI-3413]
  app/assets/javascripts/protocols/steps.js.erb
Labels: features/note-section

#1699 Bulk insert for SystemNotifications, updated ordering [SCI-3346]
  app/models/system_notification.rb
  app/models/user_system_notification.rb
  app/services/notifications/handle_system_notification_in_communication_channel_service.rb
  app/services/notifications/push_to_communication_channel_service.rb
  app/services/notifications/sync_system_notifications_service.rb
  app/views/system_notifications/_notification.html.erb
  db/migrate/20190424113216_add_unique_index_to_system_notifications.rb
  db/schema.rb
  spec/factories/system_notifications.rb
  spec/models/system_notification_spec.rb
  spec/models/user_system_notification_spec.rb
  spec/services/notifications/handle_system_notification_in_communication_channel_service_spec.rb
  spec/services/notifications/push_to_communication_channel_service_spec.rb
  spec/services/notifications/sync_system_notifications_service_spec.rb
Labels: master

#1734 Fix task tag cut off [SCI-3414]
  app/assets/javascripts/my_modules.js
  app/assets/javascripts/select2_customization.js
Labels: features/note-section

#1738 Fix protocol update error, rollback bootstrap gems and fix step name [SCI-3424][SCI-3427]
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/steps.scss
  app/models/protocol.rb
  app/views/steps/_step.html.erb
Labels: features/note-section

#1736 Add old tinymce image support [SCI-3423]
  app/models/concerns/tiny_mce_images.rb
  app/models/tiny_mce_asset.rb
Labels: features/note-section

#1735 Change dropdown highlight color and fix task tag position [SCI-3410]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/select2_customizations.scss
Labels: features/note-section

#1743 Fix tiny mce visuals, saving and cursor position [SCI-3386]
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/stylesheets/tiny_mce.scss
Labels: features/note-section

#1748 Fix report saving [SCI-3443]
  app/helpers/reports_helper.rb
  app/models/concerns/tiny_mce_images.rb
  app/models/report.rb
  app/models/report_element.rb
  app/views/reports/elements/_my_module_protocol_element.html.erb
  config/initializers/extends.rb
Labels: features/note-section

#1751 Fix step comments bugs [SCI-3440]
  app/assets/javascripts/comments.js.erb
  app/assets/stylesheets/steps.scss
Labels: features/note-section

#1749 Fix protocol preview name [SCI-3450]
  app/assets/javascripts/my_modules/protocols.js.erb
  app/helpers/protocol_status_helper.rb
Labels: features/note-section

#1729 Update protocol preview style [SCI-3416]
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/protocols/preview_modal.scss
  app/assets/stylesheets/protocols/protocol.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/my_modules/results.html.erb
  app/views/protocols/_header.html.erb
  app/views/protocols/_steps.html.erb
  app/views/protocols/edit.html.erb
  app/views/protocols/index.html.erb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  app/views/reports/new.html.erb
  app/views/search/results/_protocols.html.erb
  app/views/shared/_formulas_libraries.html.erb
  app/views/steps/_step.html.erb
  app/views/steps/attachments/_list.html.erb
Labels: features/note-section

#1745 Fix attachment appearance after update [SCI-3437]
  app/controllers/assets_controller.rb
  app/models/step.rb
Labels: features/note-section

#1746 Changes to create new office file button [SCI-3426]
  app/assets/images/office/office.svg
  app/assets/javascripts/assets/wopi/create_wopi_file.js
  app/assets/stylesheets/my_modules.scss
  app/controllers/assets_controller.rb
  app/helpers/application_helper.rb
  app/views/assets/wopi/_create_wopi_file_button.html.erb
  app/views/assets/wopi/_file_wopi_controls.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
Labels: master

#1747 Fix TinyMCE images in task description and task protocol description view [SCI-3438]
  app/views/my_modules/_module_header.html.erb
  app/views/my_modules/protocols.html.erb
Labels: master

#1750 Fix zoom on Y axis [SCI-3374]
  app/assets/javascripts/sitewide/file_preview.js
Labels: features/note-section

#1755 Change author of copied inventory item [SCI-3349]
  app/services/repository_actions/duplicate_rows.rb
Labels: master

#1757 Note section GUI fixes [SCI-3453]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/protocols/_protocol_buttons.html.erb
  app/views/my_modules/protocols/_protocol_status_bar_buttons.html.erb
Labels: master

#1761 Fix broken global activities team filter [SCI-3456]
  app/models/team.rb
Labels: master

#1774 Fix bug with external TinyMCE assets
  app/models/tiny_mce_asset.rb
Labels: master

#1764 Add base class for normalizer [SCI-3431]
  app/utilities/protocol_importers/protocol_normalizer.rb
  spec/utilities/protocol_importers/protocol_normalizer_spec.rb
Labels: features/protocolsio_integration

#1775 JSON structure and basic normalizer for ProtocolsIO [SCI-3432]
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  app/utilities/protocol_importers/protocols_io/v3/step_components.rb
  config/initializers/constants.rb
  spec/fixtures/files/protocols_io/v3/normalized_single_protocol.json
  spec/fixtures/files/protocols_io/v3/single_protocol.json
  spec/utilities/protocol_importers/protocols_io/v3/protocol_normalizer_spec.rb
Labels: do-not-review :warning:, features/protocolsio_integration

#1785 Update protocol status bar upon protocol changing [SCI-3193]
  app/assets/javascripts/my_modules/protocols.js.erb
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/controllers/assets_controller.rb
Labels: master

#1780 Add a startup check for WOPI_ENABLED == true variables
  app/models/asset.rb
  config/initializers/wopi_startup_check.rb
Labels: master

#1796 Fix the user.activities association so it works [SCI-3494]
  app/models/user.rb
Labels: master

#1653 Migrate emails from billing to common addons, update styling [SCI-3140]
  test/mailers/previews/app_mailer_preview.rb
Labels: master

#1802 Hide create office file button to user without permission [SCI-3470]
  app/views/steps/attachments/_list.html.erb
Labels: master
