Repository scinote-eln/scinote-web, pull requests merged in 2019-11, with the labels that each got.

#2211 RC << Features/task api endpoints
  .rubocop.yml
  app/controllers/api/v1/assets_controller.rb
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/results_controller.rb
  app/controllers/api/v1/steps_controller.rb
  app/controllers/api/v1/tasks_controller.rb
  app/models/asset.rb
  app/models/my_module.rb
  app/serializers/api/v1/asset_serializer.rb
  app/serializers/api/v1/protocol_serializer.rb
  app/serializers/api/v1/step_serializer.rb
  config/locales/en.yml
  config/routes.rb
  lib/tasks/my_modules.rake
  spec/factories/my_modules.rb
  spec/fixtures/files/apple.jpg
  spec/lib/tasks/my_modules_spec.rb
  spec/models/experiment_spec.rb
  spec/models/my_module_spec.rb
  spec/requests/api/v1/assets_controller_spec.rb
  spec/requests/api/v1/results_controller_spec.rb
  spec/requests/api/v1/steps_controller_spec.rb
  spec/requests/api/v1/tasks_controller_spec.rb
  spec/services/model_importers/test_experiment_data/experiment.json
Labels: NextRelease

#2199 Fix eln export for file without extension [SCI-4055]
  app/models/tiny_mce_asset.rb
Labels: priority

#2207 Add auto-save feature to text fields [SCI-4004]
  app/assets/javascripts/shared/inline_editing.js
  app/assets/javascripts/sitewide/comments.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/javascripts/users/settings/teams/invite_users_modal.js
  app/assets/javascripts/users/settings/teams/show.js
  app/assets/stylesheets/partials/_inline_editing.scss
  app/assets/stylesheets/protocols/protocol.scss
  app/assets/stylesheets/settings/teams.scss
  app/assets/stylesheets/settings/users.scss
  app/assets/stylesheets/shared/comments.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/protocols_controller.rb
  app/controllers/users/settings/teams_controller.rb
  app/models/team.rb
  app/views/my_modules/_description_form.html.erb
  app/views/my_modules/protocols/_protocol_description_form.html.erb
  app/views/protocols/_header.html.erb
  app/views/protocols/edit.html.erb
  app/views/protocols/header/_authors_label.html.erb
  app/views/protocols/header/_edit_authors_modal_body.html.erb
  app/views/protocols/header/_edit_metadata_modal.html.erb
  app/views/protocols/header/_edit_name_modal_body.html.erb
  app/views/protocols/header/_name_label.html.erb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  app/views/repositories/show.html.erb
  app/views/shared/_inline_editing.html.erb
  app/views/shared/_navigation.html.erb
  app/views/shared/_secondary_navigation.html.erb
  app/views/shared/_tiny_mce_editor.html.erb
  app/views/shared/comments/_item.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/settings/teams/_breadcrumbs.html.erb
  app/views/users/settings/teams/_name_modal.html.erb
  app/views/users/settings/teams/_name_modal_body.html.erb
  app/views/users/settings/teams/show.html.erb
  config/locales/en.yml
  config/routes.rb
  features/settings_page/profile.feature
  features/settings_page/team.feature
  features/step_definitions/shared_steps.rb
  spec/controllers/protocols_controller_spec.rb
Labels: priority

#2209 External image download improvement [SCI-4077]
  Gemfile
  Gemfile.lock
  app/models/concerns/tiny_mce_images.rb
Labels: priority

#2192 Enabling tests for projects page [SCI-4017]
  features/home_page.feature.pending
  features/projects_page/project_archiving.feature
  features/projects_page/project_comments.feature
  features/projects_page/project_managing.feature
  features/projects_page/project_users.feature
  features/step_definitions/projects_page_steps.rb
  features/step_definitions/shared_steps.rb
Labels: do-not-review :warning:, features/cucumbers 🥒

#2176 Enable Teams cucumber tests [SCI-4022]
  features/step_definitions/shared_steps.rb
  features/step_definitions/team_steps.rb
  features/support/env.rb
  features/teams.feature
  features/teams.feature.pending
Labels: do-not-review :warning:, features/cucumbers 🥒

#2166 StatusItems API endpoint [SCI-3996]
  app/controllers/api/v1/inventory_columns_controller.rb
  app/controllers/api/v1/inventory_status_items_controller.rb
  app/models/repository_column.rb
  app/serializers/api/v1/inventory_column_serializer.rb
  app/serializers/api/v1/inventory_status_item_serializer.rb
  config/initializers/extends.rb
  config/routes.rb
  spec/requests/api/v1/inventory_columns_controller_spec.rb
  spec/requests/api/v1/inventory_status_items_controller_spec.rb
  spec/support/api/schemas/status_items/collection.json
  spec/support/api/schemas/status_items/item.json
  spec/support/api/schemas/status_items/resource.json
Labels: features/new-column-types

#2203 Finish modals for manage column types (File, Text, Statuses, Lists)[SCI-3922]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repository_columns/columns_initializers/list_column_type.js
  app/assets/javascripts/repository_columns/columns_initializers/status_column_type.js
  app/assets/javascripts/repository_columns/index.js
  app/assets/javascripts/sitewide/constants.js.erb
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/repository_columns/index.scss
  app/assets/stylesheets/repository_columns/list_type.scss
  app/assets/stylesheets/repository_columns/status_type.scss
  app/controllers/repository_columns/asset_columns_controller.rb
  app/controllers/repository_columns/list_columns_controller.rb
  app/controllers/repository_columns/status_columns_controller.rb
  app/controllers/repository_columns/text_columns_controller.rb
  app/controllers/repository_columns_controller.rb
  app/helpers/repository_columns_helper.rb
  app/serializers/repository_column_serializer.rb
  app/services/repository_columns/update_column_service.rb
  app/services/repository_columns/update_list_column_service.rb
  app/views/repository_columns/_manage_column_modal.html.erb
  app/views/repository_columns/_manage_column_modal_content.html.erb
  app/views/repository_columns/manage_column_partials/_asset.html.erb
  app/views/repository_columns/manage_column_partials/_list.html.erb
  app/views/repository_columns/manage_column_partials/_status.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  db/migrate/20191105143702_add_delimiter_to_repository_column.rb
  db/structure.sql
  spec/controllers/repository_columns/list_columns_controller_spec.rb
  spec/services/repository_columns/update_list_column_service_spec.rb
Labels: features/new-column-types

#2180 Update js load order
  app/assets/javascripts/application.js.erb
Labels: features/new-column-types

#2216 Refactor inventory edit mode [SCI-4070]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/forms/repository_item_edit.js
  app/assets/javascripts/repositories/renderers/edit_renderers.js
  app/assets/javascripts/repositories/renderers/new_renderers.js
  app/assets/javascripts/repositories/repository_datatable.js
  app/assets/javascripts/repositories/row_editor.js
  app/assets/javascripts/repositories/validators/base_validator.js
  app/assets/stylesheets/themes/repositories.scss
  app/helpers/repository_datatable_helper.rb
  app/models/repository_column.rb
  app/serializers/repository_datatable/repository_asset_value_serializer.rb
  app/serializers/repository_datatable/repository_list_value_serializer.rb
  app/serializers/repository_datatable/repository_status_value_serializer.rb
  app/serializers/repository_datatable/repository_text_value_serializer.rb
  app/services/repository_table_state_column_update_service.rb
  app/services/repository_table_state_service.rb
  app/views/repositories/_repository_table.html.erb
  app/views/repositories/show.html.erb
  config/initializers/constants.rb
  spec/services/repository_table_state_column_update_service_spec.rb
  spec/services/repository_table_state_service_spec.rb
  spec/support/matchers/be_valid_default_repository_state.rb
  spec/support/matchers/be_valid_repository_table_state.rb
Labels: features/new-column-types

#2206 Add File type renderer [SCI-4038]
  app/assets/javascripts/repositories/renderers/view_renderers.js
  app/assets/stylesheets/repositories.scss
  app/helpers/file_icons_helper.rb
  app/serializers/repository_datatable/repository_asset_value_serializer.rb
Labels: features/new-column-types

#2225 Add arrows control for dropdown [SCI-4089]
  app/assets/javascripts/protocols/header.js
  app/assets/javascripts/sitewide/dropdown_selector.js
  app/assets/stylesheets/shared/dropdown_selector.scss
Labels: NextRelease

#2226 Fix name update and path to team [SCI-4086]
  app/assets/javascripts/users/settings/teams/show.js
  app/controllers/users/settings/teams_controller.rb
  app/views/users/settings/teams/show.html.erb
Labels: NextRelease

#2227 Fix permission check and due date clear [SCI-4110]
  app/assets/javascripts/my_modules.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/views/my_modules/_module_header_due_date_label.html.erb
Labels: NextRelease

#2228 Add strict order to module tags in modal [SCI-4090]
  app/controllers/my_module_tags_controller.rb
Labels: NextRelease

#2230 Fix dropdown event after click browser back action [SCI-4097]
  app/assets/javascripts/sitewide/dropdown_selector.js
Labels: NextRelease

#2229 Update css for global activities page [SCI-4111]
  app/assets/stylesheets/global_activities.scss
  app/views/global_activities/_date_picker.html.erb
  app/views/global_activities/_side_filters.html.erb
  app/views/global_activities/index.html.erb
Labels: NextRelease

#2234 Fix tag edit mode [SCI-4110]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/views/my_modules/_tags.html.erb
Labels: NextRelease

#2218 Replace RTE with simple textarea [SCI-4088]
  app/assets/stylesheets/settings/teams.scss
  app/views/users/settings/teams/show.html.erb
  features/settings_page/team.feature
Labels: NextRelease

#2236 UI activtiies fixes [SCI-4117]
  app/assets/javascripts/global_activities/side_pane.js
  app/assets/javascripts/sitewide/dropdown_selector.js
  app/assets/stylesheets/shared/dropdown_selector.scss
Labels: NextRelease

#2237 Add task description and task protocol description activities [SCI-4114]
  app/controllers/my_modules_controller.rb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
Labels: NextRelease

#2238 Improve time zone and date format interaction at preference page [SCI-4101]
  app/assets/javascripts/sitewide/dropdown_selector.js
  app/assets/javascripts/users/settings/account/preferences/index.js
Labels: NextRelease

#2235 Update filter logic for activities [SCI-4116]
  app/services/activities_service.rb
Labels: NextRelease
