Repository scinote-eln/scinote-web, pull requests merged in 2019-06, with the labels that each got.

#1815 Rename permision_eval - permission_eval [SCI-2991]
  app/services/smart_annotations/permission_eval.rb
  app/services/smart_annotations/tag_to_html.rb
  app/services/smart_annotations/tag_to_text.rb
  spec/services/smart_annotations/permission_eval_spec.rb
Labels: master

#1790 Add ProtocolIntermediateObject [SCI-3360][SCI-3361]
  app/models/step.rb
  app/utilities/protocol_importers/attachments_builder.rb
  app/utilities/protocol_importers/protocol_description_builder.rb
  app/utilities/protocol_importers/protocol_intermediate_object.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  app/utilities/protocol_importers/protocols_io/v3/step_components.rb
  app/utilities/protocol_importers/step_description_builder.rb
  app/utilities/protocol_importers/tables_builder.rb
  app/views/protocol_importers/templates/_amount.html.erb
  app/views/protocol_importers/templates/_command.html.erb
  app/views/protocol_importers/templates/_concentration.html.erb
  app/views/protocol_importers/templates/_dataset.html.erb
  app/views/protocol_importers/templates/_details.html.erb
  app/views/protocol_importers/templates/_duration.html.erb
  app/views/protocol_importers/templates/_gotostep.html.erb
  app/views/protocol_importers/templates/_link.html.erb
  app/views/protocol_importers/templates/_note.html.erb
  app/views/protocol_importers/templates/_reagent.html.erb
  app/views/protocol_importers/templates/_result.html.erb
  app/views/protocol_importers/templates/_software.html.erb
  app/views/protocol_importers/templates/_temperature.html.erb
  app/views/protocol_importers/templates/_warning.html.erb
  app/views/protocol_importers/templates/protocol_description.html.erb
  app/views/protocol_importers/templates/step_description.html.erb
  config/locales/protocols/en.yml
  spec/fixtures/files/protocols_importer/description_with_body.json
  spec/fixtures/files/protocols_importer/description_with_body_html.json
  spec/fixtures/files/protocols_importer/description_with_extra_content.json
  spec/fixtures/files/protocols_importer/description_with_image.json
  spec/fixtures/files/protocols_importer/protocols_io/v3/normalized_single_protocol.json
  spec/fixtures/files/protocols_importer/protocols_io/v3/single_protocol.json
  spec/fixtures/files/protocols_importer/step_description_with_components.json
  spec/fixtures/files/protocols_importer/step_with_attachments.json
  spec/fixtures/files/protocols_io/v3/normalized_single_protocol.json
  spec/fixtures/files/protocols_io/v3/single_protocol.json
  spec/utilities/protocol_importers/attachments_builder_spec.rb
  spec/utilities/protocol_importers/protocol_description_builder_spec.rb
  spec/utilities/protocol_importers/protocol_intermediate_object_spec.rb
  spec/utilities/protocol_importers/protocols_io/v3/protocol_normalizer_spec.rb
  spec/utilities/protocol_importers/step_description_builder_spec.rb
  spec/utilities/protocol_importers/tables_builder_spec.rb
Labels: features/protocolsio_integration

#1823 Add document file preview generation with LibreOffice [SCI-3145]
  Dockerfile
  Dockerfile.production
  Gemfile
  Gemfile.lock
  app/models/asset.rb
  app/views/shared/_file_preview_icon.html.erb
  app/views/steps/attachments/_item.html.erb
  app/views/steps/attachments/_placeholder.html.erb
  config/initializers/constants.rb
  config/initializers/paperclip.rb
  lib/paperclip_processors/custom_file_preview.rb
  public/images/large/processing.gif
Labels: do-not-review :warning:

#1824 Change import protocol service to build protocol service [SCI-3544]
  app/services/protocol_importers/build_protocol_from_client_service.rb
  app/services/protocols/import_protocol_from_client_service.rb
  app/utilities/protocol_importers/protocol_normalizer.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  spec/services/protocol_importers/build_protocol_from_client_service_spec.rb
  spec/utilities/protocol_importers/protocol_normalizer_spec.rb
  spec/utilities/protocol_importers/protocols_io/v3/protocol_normalizer_spec.rb
Labels: features/protocolsio_integration

#1807 Fix some css on step panel heading [SCI-3508]
  app/assets/stylesheets/steps.scss
Labels: master

#1828 Import protocol service with controller params [SCI-3545]
  app/services/protocol_importers/import_protocol_service.rb
  spec/factories/tables.rb
  spec/services/protocol_importers/import_protocol_service_spec.rb
Labels: features/protocolsio_integration

#1836 Implement basic controller for protocols.io API importer [SCI-3532, 3533]
  app/controllers/external_protocols_controller.rb
  app/services/protocol_importers/build_protocol_from_client_service.rb
  app/views/protocol_importers/_import_form.html.erb
  app/views/protocol_importers/_list_of_protocol_cards.html.erb
  app/views/protocol_importers/_protocol_card.html.erb
  config/routes.rb
  spec/controllers/external_protocols_controller_spec.rb
  spec/services/protocol_importers/build_protocol_from_client_service_spec.rb
Labels: features/protocolsio_integration

#1846 Add Warnings, Before start and Guidelines to protocol description [SCI-3548]
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  app/views/protocol_importers/templates/protocol_description.html.erb
  spec/fixtures/files/protocol_importers/normalized_single_protocol.json
  spec/utilities/protocol_importers/protocol_description_builder_spec.rb
Labels: features/protocolsio_integration

#1848 Required fields not imported [SCI-3541]
  app/utilities/protocol_importers/protocol_intermediate_object.rb
  app/utilities/protocol_importers/step_description_builder.rb
  app/utilities/protocol_importers/tables_builder.rb
  app/views/protocol_importers/templates/protocol_description.html.erb
  app/views/protocol_importers/templates/step_description.html.erb
  config/initializers/constants.rb
  spec/fixtures/files/protocol_importers/description_with_body_html.json
  spec/utilities/protocol_importers/step_description_builder_spec.rb
  spec/utilities/protocol_importers/tables_builder_spec.rb
Labels: features/protocolsio_integration

#1864 Fix i18n object for header [SCI-3609]
  app/services/reports/docx/draw_my_module_repository.rb
  app/services/reports/docx/private_methods.rb
Labels: features/docx-report

#1863 Fix file error in inventory cell for docx [SCI-3608]
  app/helpers/repository_datatable_helper.rb
Labels: features/docx-report

#1852 Change UI for new report download selector [SCI-3574]
  app/assets/javascripts/reports/new.js
  app/assets/stylesheets/reports.scss
  app/controllers/reports_controller.rb
  app/views/reports/new/_report_navigation.html.erb
  config/locales/en.yml
Labels: features/docx-report

#1850 When a user clicks on a protocol, protocol preview should be re…
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/assets/stylesheets/protocol_management.scss
  app/views/protocols/index.html.erb
  app/views/protocols/index/_external_protocols_tab.html.erb
  config/initializers/assets.rb
Labels: features/protocolsio_integration

#1869 Implement protocols.io error handling
  app/controllers/external_protocols_controller.rb
  app/services/protocol_importers/build_protocol_from_client_service.rb
  app/services/protocol_importers/search_protocols_service.rb
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  app/utilities/protocol_importers/protocols_io/v3/errors.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  spec/services/protocol_importers/build_protocol_from_client_service_spec.rb
  spec/services/protocol_importers/search_protocols_service_spec.rb
  spec/utilities/protocol_importers/protocols_io/v3/api_client_spec.rb
  spec/utilities/protocol_importers/protocols_io/v3/protocol_normalizer_spec.rb
Labels: features/protocolsio_integration

#1866 Import protocol modal with preview [SCI-3564] & [SCI-3568]
  app/assets/javascripts/sitewide/external_protocols.js
  app/assets/stylesheets/protocols/preview_modal.scss
  app/controllers/external_protocols_controller.rb
  app/services/protocol_importers/build_protocol_from_client_service.rb
  app/services/protocol_importers/import_protocol_service.rb
  app/utilities/protocol_importers/attachments_builder.rb
  app/utilities/protocol_importers/protocol_intermediate_object.rb
  app/views/protocol_importers/_import_form.html.erb
  app/views/protocol_importers/_preview_modal_footer.html.erb
  app/views/protocols/index/_external_protocols_tab.html.erb
  app/views/steps/_step.html.erb
  app/views/steps/attachments/_new_attachment.html.erb
  app/views/steps/attachments/_preview_list.html.erb
  config/locales/en.yml
  config/locales/protocols/en.yml
  spec/controllers/external_protocols_controller_spec.rb
  spec/services/protocol_importers/build_protocol_from_client_service_spec.rb
  spec/services/protocol_importers/import_protocol_service_spec.rb
  spec/utilities/protocol_importers/attachments_builder_spec.rb
  spec/utilities/protocol_importers/protocol_intermediate_object_spec.rb
Labels: features/protocolsio_integration

#1860 Refactor API connector for marvinJS
  app/assets/javascripts/marvinjs_editor.js
  app/assets/stylesheets/marvinjs.scss
  app/helpers/my_modules_helper.rb
  app/views/shared/_marvinjs_modal.html.erb
Labels: features/marvinjs-integration

#1870 Prepare styled listing of protocols [SCI-3535]
  app/assets/javascripts/protocols/external_protocols_tab.js
  app/assets/javascripts/sitewide/external_protocols.js
  app/assets/stylesheets/protocol_management.scss
  app/controllers/external_protocols_controller.rb
  app/services/protocol_importers/search_protocols_service.rb
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
  app/views/protocol_importers/_list_of_protocol_cards.html.erb
  app/views/protocol_importers/_protocol_card.html.erb
  app/views/protocols/index/_external_protocols_tab.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  config/locales/protocols/en.yml
  spec/fixtures/files/protocol_importers/normalized_list.json
Labels: features/protocolsio_integration
