Repository scinote-eln/scinote-web, pull requests merged in 2019-09, with the labels that each got.

#2022 Change inline editing css, add shared inventory subtitle… [SCI-3811]
  app/assets/javascripts/shared/inline_editing.js
  app/assets/stylesheets/partials/_inline_editing.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/repositories_controller.rb
  app/helpers/icons_helper.rb
  app/helpers/inventories_helper.rb
  app/views/my_modules/_repositories_dropdown.html.erb
  app/views/repositories/show.html.erb
  app/views/shared/_inline_editing.html.erb
  config/locales/en.yml
Labels: features/inventory-improvements, master

#2024 Fix padding for share modal [SCI-3824]
  app/assets/stylesheets/repositories.scss
Labels: features/inventory-improvements

#2029 Fix the failing Cucumber test for uploading avatar
  features/assets/Moon.png
Labels: master

#2031 Fix bug on API endpoint when creating result [SCI-3819]
  app/controllers/api/v1/results_controller.rb
Labels: core-api

#2004 Fix new office file creation [SCI-3778]
  app/controllers/api/v1/results_controller.rb
  app/controllers/assets_controller.rb
  app/models/asset.rb
  config/initializers/api.rb
Labels: Active Storage

#2030 Fix global activities jsonb field [SCI-3830]
  app/helpers/global_activities_helper.rb
  app/models/concerns/activity_values_model.rb
  app/views/global_activities/references/_experiment.html.erb
  app/views/global_activities/references/_my_module.html.erb
  app/views/global_activities/references/_project.html.erb
  app/views/global_activities/references/_protocol.html.erb
  app/views/global_activities/references/_report.html.erb
  app/views/global_activities/references/_repository.html.erb
  app/views/global_activities/references/_result.html.erb
  app/views/global_activities/references/_team.html.erb
  db/migrate/20190903145834_convert_activities_json_to_jsonb.rb
  db/schema.rb
  spec/models/activity_spec.rb
  spec/services/activities/create_activity_service_spec.rb
Labels: features/global-activities

#2019 Fix import items to inventory [SCI-3769]
  app/services/spreadsheet_parser.rb
Labels: Active Storage

#2033 Minor typo fix in RSpec tests
  spec/requests/api/v1/inventory_list_items_controller_spec.rb
Labels: master

#2037 Remove link to archived project page [SCI-3842]
  app/views/search/results/partials/_project_text.html.erb
Labels: master

#2026 Fix new step button on empty task [SCI-3826]
  app/assets/javascripts/protocols/steps.js.erb
Labels: master

#2035 Add local sorting for ProtocolsIO [SCI-3827]
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  app/utilities/protocol_importers/protocols_io/v3/protocol_normalizer.rb
Labels: master

#2036 Improve behavior of inventory items export modal [SCI-3815]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/controllers/repositories_controller.rb
  app/views/repositories/_export_repository_modal.html.erb
  config/locales/en.yml
Labels: master

#2023 Update trim_html_tags Postgres function [SCI-3726]
  db/migrate/20190830141257_update_trim_html_tags_function.rb
  db/schema.rb
Labels: master

#2039 Fix permission check for inventory [SCI-3844]
  app/services/smart_annotations/permission_eval.rb
Labels: master

#2041 Fix missing icon on shared inventories in global search [SCI-3847]
  app/controllers/search_controller.rb
  app/helpers/inventories_helper.rb
  app/views/search/index.html.erb
Labels: master, priority

#2042 Hotfix september
  VERSION
  app/controllers/api/v1/results_controller.rb
Labels: master

#2045 Update canaid Gem reference in Gemfile to use tags, not master
  Gemfile
  Gemfile.lock
Labels: master

#1983 Fix report image issues [SCI-3772]
  app/helpers/reports_helper.rb
  app/models/asset.rb
  app/models/concerns/image_variant_processing.rb
  app/models/user.rb
  app/services/reports/docx/draw_result_asset.rb
  app/services/reports/docx/draw_step_asset.rb
  app/services/reports/docx/private_methods.rb
Labels: Active Storage

#2056 Fix path to icon for chemical structure [SCI-3884]
  app/assets/stylesheets/steps.scss
Labels: features/marvinjs-integration

#2057 Fix duplicate MarvinJS save [SCI-3882]
  app/assets/javascripts/sitewide/marvinjs_editor.js
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/marvin_js_assets_controller.rb
  config/locales/en.yml
Labels: features/marvinjs-integration

#2063 Fix hidden buttons in inventory [SCI-3883]
  app/assets/javascripts/repositories/repository_datatable.js
Labels: Active Storage

#2064 Fix file preview in inventory [SCI-3873]
  app/views/shared/_asset_link.html.erb
Labels: Active Storage

#2065 Fix step table error [SCI-3879]
  app/assets/javascripts/my_modules/results.js
  app/assets/javascripts/protocols/steps.js.erb
Labels: Active Storage

#2066 Fix missing expand all button [SCI-3878]
  app/assets/javascripts/protocols/steps.js.erb
  app/views/protocols/_steps.html.erb
Labels: Active Storage

#2067 Fix error when save report to inventory [SCI-3880]
  app/services/report_actions/save_pdf_to_inventory_item.rb
Labels: Active Storage

#2070 Error handling, when image unavaliable for base64 [SCI-3874]
  app/models/concerns/image_variant_processing.rb
Labels: Active Storage

#2071 Fix error on archived experiment page [SCI-3889]
  app/views/projects/experiment_archive/_experiment.html.erb
Labels: Active Storage

#1964 Add text extraction from MarvinJS for search [SCI-3643]
  app/models/asset.rb
  app/services/marvin_js_service.rb
Labels: Active Storage

#2074 [SCI-3875] Content is not saved for office files
  app/controllers/wopi_controller.rb
Labels: Active Storage

#2081 Fix JS error in recent protocol drop down [SCI-3901]
  app/assets/javascripts/my_modules/protocols.js
Labels: Active Storage

#2076 Fix repository row import/export [SCI-3769]
  app/assets/javascripts/repositories/repository_datatable.js
  app/controllers/zip_exports_controller.rb
  app/services/spreadsheet_parser.rb
Labels: Active Storage

#2051 Create task API endpoint [SCI-3834]
  app/controllers/api/v1/tasks_controller.rb
  app/models/my_module.rb
  config/locales/en.yml
  config/routes.rb
  spec/factories/my_modules.rb
  spec/models/experiment_spec.rb
  spec/models/my_module_spec.rb
  spec/requests/api/v1/tasks_controller_spec.rb
  spec/services/model_importers/test_experiment_data/experiment.json
Labels: core-api

#2082 Fix dirty event after update marvinjs image [SCI-3907]
  app/assets/javascripts/sitewide/marvinjs_editor.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/javascripts/tinymce/plugins/custom_image_toolbar/plugin.js
Labels: Active Storage

#2058 Create Protocol step API endpoint [SCI-3835]
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/steps_controller.rb
  app/serializers/api/v1/protocol_serializer.rb
  app/serializers/api/v1/step_serializer.rb
  config/routes.rb
  spec/requests/api/v1/steps_controller_spec.rb
Labels: core-api

#2069 Fix inventory item selection when previewing file [SCI-3796]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: master

#2078 Fix bug with inventory navigation height [SCI-3906]
  app/assets/stylesheets/partials/_tree_view.scss
Labels: master

#2077 Expand clickable area of links in secondary navigation [SCI-3764]
  app/assets/stylesheets/partials/_tree_view.scss
Labels: master

#2093 ActiveMailer minor config changes
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: master

#2061 [SCI-3784] Small RTF improvements
  app/assets/stylesheets/hooks/tinymce.scss
Labels: master

#2068 Fix reloading of datatables header [SCI-3816]
  app/assets/javascripts/repositories/repository_datatable.js.erb
Labels: master

#2091 Fix cancel button for marvinJS images [SCI-3907]
  app/assets/javascripts/sitewide/marvinjs_editor.js
Labels: Active Storage

#2096 Fix tinymce assets render in report [SCI-3932]
  app/models/concerns/tiny_mce_images.rb
Labels: Active Storage

#2097 Fix preview for result [SCI-3930]
  app/controllers/assets_controller.rb
  app/views/my_modules/_result_user_generated.html.erb
Labels: Active Storage

#2062 Fix routes for addons installer
  config/routes.rb
Labels: Active Storage

#2053 Redesign of sorting button for projects/experiments cards [SCI-3637]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/projects.scss
  app/controllers/projects_controller.rb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/steps/attachments/_list.html.erb
  config/locales/en.yml
Labels: master

#2102 Fixed missing border, counter, buttons position [SCI-3929]
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/views/my_modules/protocols/_protocol_buttons.html.erb
Labels: Active Storage
