Repository scinote-eln/scinote-web, pull requests merged in 2019-02, with the labels that each got.

#1472 System Notifications - Migration of existing data
  lib/tasks/notifications.rake
Labels: features/system-notifications

#1481 Experiment image is not updated after move of an experiment to another project [SCI-3003]
  app/services/experiments/move_to_project_service.rb
Labels: master

#1483 Test experiment import [SCI-2946]
  app/services/team_importer.rb
  spec/services/model_importers/team_importer_spec.rb
  spec/services/model_importers/test_experiment_data/assets/1/samples.txt
  spec/services/model_importers/test_experiment_data/assets/21/100gen_line_bending.png
  spec/services/model_importers/test_experiment_data/assets/8/G2938-90034_KitRNA6000Nano_ebook.pdf
  spec/services/model_importers/test_experiment_data/assets/9/Bioanalyser_result.JPG
  spec/services/model_importers/test_experiment_data/experiment.json
Labels: features/templates

#1479 Optionally disable Tika background mode through env variable [SCI-2967]
  app/models/asset.rb
Labels: master

#1489 Add templates [SCI-2938]
  app/assets/templates/experiment_422/experiment.json
  app/assets/templates/experiment_423/experiment.json
  app/assets/templates/experiment_430/assets/2838/Example.png
  app/assets/templates/experiment_430/assets/2839/Example.png
  app/assets/templates/experiment_430/assets/3096/Example.png
  app/assets/templates/experiment_430/assets/3097/Streaking_bacteria_method.png
  app/assets/templates/experiment_430/assets/3358/Streaking_bacteria_method.png
  app/assets/templates/experiment_430/assets/3410/Streak_plate.PNG
  app/assets/templates/experiment_430/experiment.json
  app/assets/templates/experiment_433/experiment.json
  app/assets/templates/experiment_436/experiment.json
  app/assets/templates/experiment_440/assets/3631/Plate_streaking.png
  app/assets/templates/experiment_440/assets/3633/gram-stain-procedure.png
  app/assets/templates/experiment_440/assets/3636/acid-fast_stain.png
  app/assets/templates/experiment_440/experiment.json
  app/assets/templates/experiment_454/assets/3628/Bottom_up_proteomics.PNG
  app/assets/templates/experiment_454/assets/3629/Bottom_up_proteomics.PNG
  app/assets/templates/experiment_454/assets/3630/Bottom_up_proteomics.PNG
  app/assets/templates/experiment_454/experiment.json
  app/assets/templates/experiment_497/assets/3624/SDS_page_electrophoresis.PNG
  app/assets/templates/experiment_497/assets/3625/Separation_of_protein_mixture.PNG
  app/assets/templates/experiment_497/assets/3626/Western_Blot_transfer.PNG
  app/assets/templates/experiment_497/assets/3627/Detection.PNG
  app/assets/templates/experiment_497/experiment.json
Labels: features/templates

#1490 Add templates after protocol_keyword_team rake task was run [SCI-2938]
  app/assets/templates/experiment_422/experiment.json
  app/assets/templates/experiment_423/experiment.json
  app/assets/templates/experiment_430/assets/2838/Example.png
  app/assets/templates/experiment_430/assets/3096/Example.png
  app/assets/templates/experiment_430/assets/3097/Streaking_bacteria_method.png
  app/assets/templates/experiment_430/experiment.json
  app/assets/templates/experiment_433/experiment.json
  app/assets/templates/experiment_436/experiment.json
  app/assets/templates/experiment_440/experiment.json
  app/assets/templates/experiment_454/experiment.json
  app/assets/templates/experiment_497/experiment.json
Labels: features/templates

#1491 Remove electronic signatures from templates [SCI-2938]
  app/assets/templates/experiment_422/experiment.json
  app/assets/templates/experiment_423/experiment.json
  app/assets/templates/experiment_430/experiment.json
  app/assets/templates/experiment_433/experiment.json
  app/assets/templates/experiment_436/experiment.json
  app/assets/templates/experiment_440/experiment.json
  app/assets/templates/experiment_454/experiment.json
  app/assets/templates/experiment_497/experiment.json
Labels: features/templates

#1482 System Notifications - View All Page [SCI-2956 and SCI-3001]
  Gemfile
  Gemfile.lock
  app/assets/javascripts/system_notifications/index.js
  app/assets/stylesheets/system_notifications.scss
  app/controllers/system_notifications_controller.rb
  app/models/system_notification.rb
  app/models/user_system_notification.rb
  app/views/system_notifications/_list.html.erb
  app/views/system_notifications/_notification.html.erb
  app/views/system_notifications/index.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/routes.rb
  db/seeds.rb
Labels: features/system-notifications

#1493 Add flag for archived tasks to experiment exporter [SCI-3033]
  app/models/experiment.rb
  app/models/my_module_group.rb
  app/services/model_exporters/experiment_exporter.rb
  spec/services/templates_service_spec.rb
Labels: features/templates

#1484 System notification modal window [SCI-2957 and SCI-2958]
  app/assets/javascripts/system_notifications/index.js
  app/controllers/system_notifications_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/system_notification.rb
  app/models/user.rb
  app/models/user_system_notification.rb
  app/views/layouts/application.html.erb
  app/views/system_notifications/_notification.html.erb
  app/views/system_notifications/_system_notification_modal.html.erb
  app/views/system_notifications/index.html.erb
  config/routes.rb
  db/seeds.rb
  yarn.lock
Labels: features/system-notifications

#1492 Fix protocols in team export service [SCI-3037]
  app/services/model_exporters/experiment_exporter.rb
  app/services/model_exporters/model_exporter.rb
  app/services/model_exporters/team_exporter.rb
Labels: features/templates

#1498 System notification navbar menu drop down [SCI 2955]
  app/assets/javascripts/navigation.js
  app/assets/javascripts/system_notifications/index.js
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/system_notifications_controller.rb
  app/models/user_system_notification.rb
  app/views/layouts/application.html.erb
  app/views/shared/_navigation.html.erb
  app/views/system_notifications/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/system_notifications_controller_spec.rb
  spec/factories/user_system_notifications.rb
  spec/models/system_notification_spec.rb
  spec/models/user_system_notification_spec.rb
Labels: features/system-notifications

#1502 Change experiments title color [SCI-3049]
  app/assets/stylesheets/themes/scinote.scss
Labels: master

#1501 Recaptcha input field now addressed with jQuery
  app/assets/javascripts/users/settings/teams/invite_users_modal.js
Labels: master

#1504 After reading What’s new notification and reloading the page, gift status is unseen again [SCI 3051]
  app/assets/javascripts/navigation.js
  app/assets/javascripts/system_notifications/index.js
  app/assets/stylesheets/system_notifications.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/views/system_notifications/_notification.html.erb
  app/views/system_notifications/index.html.erb
Labels: features/system-notifications

#1494 Changes to Activity model
  app/controllers/projects_controller.rb
  app/models/activity.rb
  app/models/user.rb
  app/services/experiments/move_to_project_service.rb
  db/migrate/20190213064847_change_table_activities.rb
  db/schema.rb
  spec/factories/activity.rb
  spec/models/activity_spec.rb
  spec/models/user_spec.rb
Labels: features/global-activities

#1508 System Notification polish🇵🇱 Email [SCI-3050]
  config/locales/en.yml
Labels: features/system-notifications

#1509 Add validation limits for system notification fields [SCI-3060]
  app/models/system_notification.rb
  spec/factories/system_notifications.rb
  spec/models/system_notification_spec.rb
Labels: features/system-notifications

#1505 Check for recaptcha enabled boolean value
  app/views/shared/_invite_users_modal.html.erb
Labels: master

#1515 Rename Demo project and create rake task to create it on existing users [SCI-3080]
  app/utilities/first_time_data_generator.rb
  lib/tasks/data.rake
Labels: master

#1507 Add action_name to sidebar cache as dependency [SCI-2930]
  app/views/shared/_sidebar.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_projects.html.erb
Labels: master

#1516 Due date is not red for today anymore [SCI-3069]
  app/models/my_module.rb
Labels: master

#1520 Copy as template on experiment card does not respond at mouse over [SCI-3081][SCI-3082]
  app/assets/javascripts/experiments/dropdown_actions.js
  app/utilities/first_time_data_generator.rb
Labels: features/templates

#1519 Adding new Select2 library with customizations
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/select2_customization.js
  app/assets/stylesheets/select2_customizations.scss
  vendor/assets/javascripts/select2.min.js
  vendor/assets/stylesheets/select2.min.css
Labels: master

#1522 Task info section improvements [SCI - 3058]
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/views/my_modules/_module_header.html.erb
  app/views/my_modules/protocols.html.erb
Labels: master

#1534 Update tooltip for system notifications dropdown
  app/views/shared/_navigation.html.erb
  config/locales/en.yml
Labels: priority

#1525 Demo project improvements [SCI-3096], [SCI-3097], [SCI-3098], [SCI-3099], [SCI-3102]
  app/utilities/first_time_data_generator.rb
  lib/tasks/data.rake
Labels: master

#1536 Missing item smart annotation in Demo project [SCI-3100, 3098]
  app/utilities/delayed_uploader_demo.rb
  app/utilities/first_time_data_generator.rb
Labels: master
