Repository scinote-eln/scinote-web, pull requests merged in 2019-04, with the labels that each got.

#1616 Change activities for task protocols [SCI-3237]
  app/controllers/protocols_controller.rb
  app/controllers/step_comments_controller.rb
  app/controllers/steps_controller.rb
  app/utilities/wopi_util.rb
  app/views/global_activities/references/_protocol.html.erb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
Labels: master

#1622 Remove JS memory leak on project index page
  app/assets/javascripts/projects/index.js
Labels: master

#1618 Missing activities, fix for showing report name, add step positions, fixed links [SCI-3240] [SCI-3246]
  app/helpers/global_activities_helper.rb
  app/models/repository.rb
  app/services/repository_actions/duplicate_rows.rb
  app/views/global_activities/references/_repository.html.erb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  spec/models/repository_spec.rb
  spec/services/repository_actions/duplicate_rows_spec.rb
Labels: master

#1633 Wrap user sign_in into rescue block [SCI-3276]
  app/controllers/users/sessions_controller.rb
Labels: master

#1634 Fix archive task translation [SCI-3288]
  config/locales/global_activities/en.yml
Labels: master

#1637 Wrong counter of step items, it now starts with one [SCI-3273]
  app/controllers/step_comments_controller.rb
  app/controllers/steps_controller.rb
  app/models/step.rb
  app/models/team_zip_export.rb
  app/utilities/wopi_util.rb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  app/views/reports/elements/_my_module_step_element.html.erb
  app/views/steps/_step.html.erb
Labels: master

#1635 Fix activities wording [SCI-3287]
  app/controllers/protocols_controller.rb
  config/locales/global_activities/en.yml
Labels: do-not-merge :warning:

#1647 Change step header, remove vertical line
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/reports/elements/_my_module_step_element.html.erb
  app/views/steps/_step.html.erb
Labels: features/scinote-improvements

#1648 Remove activities that belong to addons [SCI-3214]
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
Labels: master

#1646 Disable save button while image loading [SCI-3293]
  app/assets/javascripts/sitewide/file_preview.js
Labels: master

#1644 Add dynamic generating filters for global activities [SCI-3228]
  app/assets/javascripts/global_activities/side_pane.js
  app/assets/javascripts/select2_customization.js
  app/controllers/global_activities_controller.rb
  app/models/concerns/searchable_by_name_model.rb
  app/models/concerns/team_by_subject_model.rb
  app/models/team.rb
  app/models/user.rb
  app/views/global_activities/_side_filters.html.erb
  app/views/my_modules/activities/_side_filters.html.erb
  config/locales/global_activities/en.yml
  config/routes.rb
Labels: master

#1645 Reset counter for export [SCI-3234]
  app/controllers/teams_controller.rb
  app/models/user.rb
  config/secrets.yml
  spec/models/user_spec.rb
Labels: master

#1650 Update API endpoints for new activities [SCI-3295]
  app/controllers/api/v1/tasks_controller.rb
  app/helpers/global_activities_helper.rb
  app/serializers/api/v1/activity_serializer.rb
  app/serializers/api/v1/user_serializer.rb
Labels: master

#1561 Improve the image file upload into RTE input fields [SCI-3131]
  app/assets/javascripts/my_modules/results.js.erb
  app/assets/javascripts/results/result_texts.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/javascripts/sitewide/tiny_mce_file_upload_plugin.js
  app/assets/javascripts/sitewide/tiny_mce_file_upload_plugin.js.erb
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/hooks/tinymce.scss
  app/controllers/api/v1/results_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/protocols_controller.rb
  app/controllers/result_texts_controller.rb
  app/controllers/steps_controller.rb
  app/controllers/tiny_mce_assets_controller.rb
  app/helpers/tiny_mce_helper.rb
  app/models/concerns/tiny_mce_images.rb
  app/models/my_module.rb
  app/models/protocol.rb
  app/models/result_text.rb
  app/models/step.rb
  app/models/tiny_mce_asset.rb
  app/views/my_modules/_description_form.html.erb
  app/views/my_modules/_module_header.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/protocols/_protocol_description_form.html.erb
  app/views/protocols/header/_description_label.html.erb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  app/views/reports/elements/_my_module_element.html.erb
  app/views/reports/elements/_my_module_result_text_element.html.erb
  app/views/reports/elements/_my_module_step_element.html.erb
  app/views/result_texts/_edit.html.erb
  app/views/results/_result_text.html.erb
  app/views/steps/_empty_step.html.erb
  app/views/steps/_step.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  db/migrate/20190307102521_add_column_saved_to_tiny_mce_asset.rb
  db/migrate/20190308092130_add_polymorphic_to_tiny_mce_asset.rb
  db/schema.rb
  spec/requests/api/v1/results_controller_spec.rb
Labels: features/note-section

#1656 Release team space after update image [SCI-3299]
  app/controllers/assets_controller.rb
Labels: master

#1662 Fix user counter bug on project card [SCI-3320]
  app/assets/javascripts/projects/index.js
Labels: master

#1659 Add scroll to team selector [SCI-3296]
  app/assets/javascripts/navigation.js
  app/assets/stylesheets/themes/main_navigation.scss
  app/views/shared/_navigation.html.erb
Labels: master

#1657 Add check for tasks complete in project notifications [SCI-3298]
  app/models/my_module.rb
  app/models/project.rb
  app/services/projects_overview_service.rb
  app/views/projects/_notifications.html.erb
Labels: master

#1658 Fix activity card visuals [SCI-3297]
  app/assets/stylesheets/global_activities.scss
Labels: master

#1665 Disable editing of office file in view mode when module is locked [SCI-2949, 3318]
  app/controllers/wopi_controller.rb
Labels: master

#1666 Rename button load more system notification to fix the bug [SCI-3331]
  app/assets/javascripts/system_notifications/index.js
  app/assets/stylesheets/system_notifications.scss
  app/views/system_notifications/index.html.erb
Labels: master

#1668 Switch to kaminari pagination in global activities [SCI-3292]
  app/assets/javascripts/global_activities/index.js
  app/assets/javascripts/global_activities/side_pane.js
  app/controllers/global_activities_controller.rb
  app/controllers/my_modules_controller.rb
  app/services/activities_service.rb
  app/views/global_activities/index.html.erb
  app/views/my_modules/activities.html.erb
Labels: master

#1654 Add zoom to image annotation and check jpeg file quality before save [SCI-3300]
  Gemfile
  app/assets/javascripts/sitewide/file_preview.js
  app/controllers/assets_controller.rb
  app/models/asset.rb
  db/migrate/20190410110605_add_column_quality_to_asset.rb
  db/schema.rb
  lib/paperclip/image_quality_calculate.rb
Labels: master

#1649 Add ability to select filters with keyboard [SCI-3200]
  app/assets/javascripts/select2_customization.js
  app/assets/stylesheets/select2_customizations.scss
  app/controllers/global_activities_controller.rb
Labels: master

#1667 Fix links in activity message for protocols in repository [SCI-3304]
  app/helpers/global_activities_helper.rb
  app/views/global_activities/references/_protocol.html.erb
Labels: master

#1675 Fix for exports_left, fix for some edge cases [SCI-3345]
  app/controllers/teams_controller.rb
  app/models/team_zip_export.rb
  app/models/user.rb
  spec/models/user_spec.rb
Labels: priority

#1678 Fix navigationJS team switch when have only 1 team [SCI-3355]
  app/assets/javascripts/navigation.js
Labels: master, priority

#1674 Update Result API for new tiny mce image format [SCI-3265]
  app/controllers/api/v1/results_controller.rb
  spec/requests/api/v1/results_controller_spec.rb
Labels: features/note-section

#1680 Update eln export for new tinyMCE image format [SCI-3260][SCI-3261]
  app/assets/javascripts/protocols/import_export/import.js
  app/assets/javascripts/protocols/import_export/import.js.erb
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/protocols_controller.rb
  app/models/concerns/tiny_mce_images.rb
  app/models/tiny_mce_asset.rb
  app/utilities/protocols_exporter.rb
  app/utilities/protocols_importer.rb
  app/views/protocols/import_export/_import_modal.html.erb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  config/initializers/constants.rb
Labels: features/note-section

#1682 Add smooth loading for inline task and protoocl description editing
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/stylesheets/tiny_mce.scss
Labels: features/note-section

#1688 Add floating toolbar for tinymce [SCI-3168]
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/stylesheets/tiny_mce.scss
Labels: features/note-section

#1663 Migration for old tinymce assets [SCI-3176]
  db/migrate/20190307102521_add_column_saved_to_tiny_mce_asset.rb
  db/migrate/20190308092130_add_polymorphic_to_tiny_mce_asset.rb
  lib/tasks/migrate_old_tinymce_assets.rake
  lib/tasks/tiny_mce_asset.rake
  spec/factories/result.rb
  spec/factories/tinymce_assets.rb
  spec/models/tiny_mce_asset_spec.rb
Labels: features/note-section

#1683 Archived results are now separated in exported project
  app/models/team_zip_export.rb
  app/views/reports/elements/_my_module_result_asset_element.html.erb
  app/views/reports/elements/_my_module_result_table_element.html.erb
  app/views/reports/elements/_my_module_result_text_element.html.erb
Labels: master

#1652 Changes to attacmhemnts on step [SCI-3136] [SCI-3167]
  app/assets/images/office/office-online-logo.svg
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/drag_n_drop.js.erb
  app/assets/stylesheets/my_modules.scss
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/file_icons_helper.rb
  app/helpers/my_modules_helper.rb
  app/views/assets/wopi/_create_wopi_file_button.html.erb
  app/views/result_assets/_new.html.erb
  app/views/steps/_empty_step.html.erb
  app/views/steps/_form_assets.html.erb
  app/views/steps/_step.html.erb
  app/views/steps/attachments/_item.html.erb
  app/views/steps/attachments/_list.html.erb
  app/views/steps/attachments/_placeholder.html.erb
  config/locales/en.yml
Labels: features/scinote-improvements

#1689 Update protocol repository for new description format [SCI-3371]
  app/assets/javascripts/protocols/header.js.erb
  app/controllers/protocols_controller.rb
  app/models/concerns/tiny_mce_images.rb
  app/models/protocol.rb
  app/models/tiny_mce_asset.rb
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/protocols/_protocol_description_form.html.erb
  app/views/protocols/_header.html.erb
  app/views/protocols/header/_description_label.html.erb
  app/views/protocols/header/_edit_description_modal_body.html.erb
  app/views/protocols/index.html.erb
  app/views/protocols/index/_protocol_preview_modal_body.html.erb
  config/routes.rb
Labels: features/note-section

#1692 Comments section changes [SCI-3135]
  app/assets/javascripts/comments.js.erb
  app/assets/javascripts/shared/inline_editing.js
  app/assets/stylesheets/steps.scss
  app/controllers/step_comments_controller.rb
  app/views/steps/_comments.html.erb
  app/views/steps/_step.html.erb
  app/views/steps/comments/_item.html.erb
  app/views/steps/comments/_list.html.erb
  config/locales/en.yml
Labels: features/note-section

#1691 Update reports for new RTE [SCI-3263]
  app/assets/javascripts/reports/new.js
  app/assets/stylesheets/reports.scss
  app/controllers/concerns/report_actions.rb
  app/views/reports/elements/_my_module_element.html.erb
  app/views/reports/elements/_my_module_protocol_element.html.erb
  config/locales/en.yml
Labels: features/note-section

#1700 Resize image preview and change alignment of cards [SCI-3385]
  app/assets/stylesheets/constants.scss
  app/assets/stylesheets/mixins.scss
  app/assets/stylesheets/steps.scss
  app/views/steps/attachments/_item.html.erb
Labels: features/note-section

#1686 Add activity for importing inventory items [SCI-3324]
  app/controllers/repositories_controller.rb
  app/utilities/repository_import_parser/importer.rb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  spec/controllers/repositories_controller_spec.rb
Labels: master

#1694 Add zoom to image annotation [SCI-3374]
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/stylesheets/hooks/tui_image_editor.scss
Labels: features/note-section

#1702 Fix loading more activities on task page [SCI-3390]
  app/views/my_modules/activities.html.erb
Labels: master

#1701 Fix sorting by user name with search parameter in inventories [SCI-3391]
  app/services/repository_datatable_service.rb
Labels: master

#1707 Fix for inline editing on Firefox [SCI-3383]
  app/assets/stylesheets/partials/_inline_editing.scss
  app/assets/stylesheets/steps.scss
Labels: features/note-section

#1703 Remove duplicated button [SCI-3382]
  app/views/my_modules/protocols.html.erb
Labels: features/note-section

#1705 Show icons for office files [SCI-3387]
  app/helpers/file_icons_helper.rb
  app/views/steps/attachments/_placeholder.html.erb
Labels: features/note-section

#1624 Add autosave for result texts [SCI-3091]
  app/assets/javascripts/results/result_texts.js
  app/views/result_texts/_edit.html.erb
  app/views/result_texts/_new.html.erb
Labels: features/note-section

#1704 Hide icon for deleting [SCI-3388]
  app/assets/stylesheets/steps.scss
Labels: features/note-section

#1714 Add editnew action for editing new office files [SCI-3380]
  app/controllers/assets_controller.rb
  app/utilities/wopi_util.rb
Labels: features/scinote-improvements

#1712 Add new tag activtiies [SCI-3341]
  app/controllers/tags_controller.rb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  spec/controllers/tags_controller_spec.rb
Labels: features/note-section

#1711 Implement API client for protocols.io [SCI-3357]
  app/utilities/protocol_importers/protocols_io/v3/api_client.rb
  config/initializers/constants.rb
  spec/utilities/protocol_importers/protocols_io/v3/api_client_spec.rb
Labels: features/protocolsio_integration

#1706 Change ownership of inventory items, when a user leaves a team [SCI-3350]
  app/models/repository_row.rb
  app/models/user_team.rb
  app/views/users/settings/user_teams/_destroy_user_team_modal_body.html.erb
  app/views/users/settings/user_teams/_leave_user_team_modal_body.html.erb
  config/locales/en.yml
Labels: master

#1716 Update project card due date dropdown [SCI-3322]
  app/assets/stylesheets/projects.scss
  app/views/projects/_notifications.html.erb
  app/views/projects/index/_project.html.erb
  config/locales/en.yml
Labels: features/note-section
