Repository scinote-eln/scinote-web, pull requests merged in 2019-01, with the labels that each got.

#1437 Change sample date in date format settings [SCI-2907]
  app/views/users/settings/account/preferences/index.html.erb
Labels: master

#1440 Merge release-1.15.2 into master
  VERSION
Labels: master

#1442 After edit step in app help does not appear any more
  app/assets/javascripts/protocols/steps.js.erb
Labels: master

#1436 Disable edit button for unsupported WOPI formats [SCI-2904]
  app/assets/javascripts/sitewide/file_preview.js.erb
  app/controllers/assets_controller.rb
  app/helpers/file_icons_helper.rb
  app/views/shared/_file_wopi_controlls.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
Labels: master

#1439 Rename CORE_API_V1_PREVIEW env. variable to CORE_API_V1_ENABLED [SCI-2888]
  app/services/api.rb
  config/initializers/api.rb
  config/routes.rb
  spec/rails_helper.rb
Labels: core-api

#1445 Fix image URLs in export all document [SCI-2931]
  app/assets/stylesheets/reports.scss
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/tiny_mce_helper.rb
  app/views/reports/elements/_my_module_result_asset_element.html.erb
  app/views/reports/elements/_my_module_result_text_element.html.erb
  app/views/reports/elements/_my_module_step_element.html.erb
  app/views/reports/elements/_step_asset_element.html.erb
Labels: master

#1449 Update Ruby to 2.4.5 and add jemalloc package
  Dockerfile
  Dockerfile.production
  Gemfile
Labels: master

#1447 Fix task tags update on canvas cards [SCI-2875]
  app/assets/javascripts/projects/canvas.js.erb
  app/controllers/my_module_tags_controller.rb
  app/views/canvas/full_zoom/_my_module.html.erb
  app/views/canvas/medium_zoom/_my_module.html.erb
  app/views/experiments/canvas.html.erb
  config/routes.rb
Labels: master

#1451 Extract the experiments export & import code from team_exporter/team_importer
  Gemfile.lock
  app/assets/javascripts/protocols/steps.js.erb
  app/services/model_exporters/experiment_exporter.rb
  app/services/model_exporters/model_exporter.rb
  app/services/model_exporters/team_exporter.rb
  app/services/team_exporter.rb
  app/services/team_importer.rb
  lib/tasks/data.rake
Labels: features/templates

#1434 Fix (unite) Date and Time display formats [SCI-2903]
  app/assets/javascripts/protocols/import_export/import.js.erb
  app/controllers/application_controller.rb
  app/helpers/protocols_io_helper.rb
  app/models/team_zip_export.rb
  app/models/zip_export.rb
  app/views/my_module_comments/_comment.html.erb
  app/views/project_comments/_comment.html.erb
  app/views/protocols/import_export/_import_json_protocol_preview_modal.html.erb
  config/routes.rb
Labels: master

#1459 Fix the Cucumber tests so they pass
  features/settings_page/team.feature
  features/step_definitions/shared_steps.rb
Labels: master

#1443 Allow org. administrators to invite them onto all projects [SCI-2914]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/themes/scinote.scss
  app/views/user_projects/_index.html.erb
Labels: master

#1466 Add libssl-1.0 to docker images [SCI-2970]
  Dockerfile
  Dockerfile.production
Labels: do-not-review :warning:

#1458 Refactor 'move_experiment' method into service object [SCI-2926]
  .rubocop.yml
  app/controllers/experiments_controller.rb
  app/models/experiment.rb
  app/models/tag.rb
  app/services/experiments/move_to_project_service.rb
  spec/controllers/projects_controller_spec.rb
  spec/factories/experiments.rb
  spec/factories/my_modules.rb
  spec/factories/tags.rb
  spec/factories/teams.rb
  spec/factories/user_project.rb
  spec/factories/user_projects.rb
  spec/models/experiment_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/v1/users_controller_spec.rb
  spec/services/experiments/move_to_project_service_spec.rb
Labels: master

#1470 Merge master into features/system-notifications
  .rubocop.yml
  Dockerfile
  Dockerfile.production
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/users/settings/teams/invite_users_modal.js
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/experiments_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/users/invitations_controller.rb
  app/models/experiment.rb
  app/models/tag.rb
  app/models/user.rb
  app/services/experiments/move_to_project_service.rb
  app/views/shared/_invite_users_modal.html.erb
  app/views/users/settings/teams/show.html.erb
  config/locales/en.yml
  db/migrate/20190117155006_change_indices_from_int_to_bigint.rb
  db/schema.rb
  lib/tasks/exportable_items.rake
  spec/controllers/projects_controller_spec.rb
  spec/factories/experiments.rb
  spec/factories/my_modules.rb
  spec/factories/tags.rb
  spec/factories/teams.rb
  spec/factories/user_project.rb
  spec/factories/user_projects.rb
  spec/models/experiment_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/v1/users_controller_spec.rb
  spec/services/experiments/move_to_project_service_spec.rb
Labels: features/system-notifications

#1448 Can not switch team [SCI-2929]
  app/controllers/application_controller.rb
Labels: master
