Repository scinote-eln/scinote-web, pull requests merged in 2019-08, with the labels that each got.

#1954 [SCI-3674] Remove width on comments
  app/assets/stylesheets/shared/comments.scss
Labels: master

#1961 [SCI-3588] Security precautions for omniauth CVE-2015-9284
  Gemfile
  Gemfile.lock
  app/views/users/shared/_links.html.erb
Labels: master

#1960 [SCI-3567] Add check_pending! call for test migrations
  spec/rails_helper.rb
Labels: master

#1956 Add additional NewStep button [SCI-3733]
  app/views/protocols/_steps.html.erb
Labels: master

#1957 Add ability to browse through shared inventories to smart annotations [SCI-3690]
  app/controllers/at_who_controller.rb
  app/services/smart_annotations/permission_eval.rb
Labels: features/inventory-improvements

#1959 Update repository index page [SCI-3736]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/extend/bootstrap.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/repositories/_columns_reorder_dropdown.html.erb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
  config/locales/en.yml
Labels: features/inventory-improvements

#1965 Share inventory popup [SCI-3737]
  app/assets/javascripts/repositories/edit.js
  app/assets/javascripts/repositories/index.js
  app/controllers/repositories_controller.rb
  app/controllers/team_repositories_controller.rb
  app/models/repository.rb
  app/services/repositories/multiple_share_update_service.rb
  app/views/repositories/_share_repository_modal.html.erb
  app/views/repositories/show.html.erb
  config/initializers/extends.rb
  config/locales/en.yml
  config/locales/global_activities/en.yml
  config/routes.rb
  spec/controllers/team_repositories_controller_spec.rb
  spec/services/repositories/multiple_share_update_service_spec.rb
Labels: features/inventory-improvements

#1972 Features/inventory improvements
  app/assets/javascripts/repositories/edit.js
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/extend/bootstrap.scss
  app/assets/stylesheets/partials/_tree_view.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/shared/icons.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/api/v1/inventory_cells_controller.rb
  app/controllers/api/v1/inventory_columns_controller.rb
  app/controllers/api/v1/inventory_items_controller.rb
  app/controllers/assets_controller.rb
  app/controllers/at_who_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/repositories_controller.rb
  app/controllers/repository_columns_controller.rb
  app/controllers/repository_list_items_controller.rb
  app/controllers/repository_rows_controller.rb
  app/controllers/search_controller.rb
  app/controllers/team_repositories_controller.rb
  app/controllers/user_repositories_controller.rb
  app/controllers/wopi_controller.rb
  app/helpers/icons_helper.rb
  app/helpers/repository_datatable_helper.rb
  app/models/repository.rb
  app/models/team.rb
  app/models/team_repository.rb
  app/permissions/repository.rb
  app/permissions/repository_column.rb
  app/permissions/team.rb
  app/services/report_actions/save_pdf_to_inventory_item.rb
  app/services/repositories/multiple_share_update_service.rb
  app/services/smart_annotations/permission_eval.rb
  app/views/repositories/_columns_reorder_dropdown.html.erb
  app/views/repositories/_share_repository_modal.html.erb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
  app/views/search/index.html.erb
  app/views/search/results/partials/_asset_text.html.erb
  app/views/search/results/partials/_repository_row_text.html.erb
  app/views/search/results/partials/_repository_text.html.erb
  config/initializers/extends.rb
  config/locales/en.yml
  config/locales/global_activities/en.yml
  config/routes.rb
  db/migrate/20190711125513_create_team_repositories.rb
  db/migrate/20190715150326_add_unique_index_to_team_repositories.rb
  db/schema.rb
  spec/controllers/team_repositories_controller_spec.rb
  spec/factories/team_repositories.rb
  spec/models/repository_spec.rb
  spec/models/team_repository_spec.rb
  spec/models/team_spec.rb
  spec/permissions/repositroy_permissions_spec.rb
  spec/requests/api/v1/inventories_controller_spec.rb
  spec/services/repositories/multiple_share_update_service_spec.rb
Labels: features/inventory-improvements, master

#1977 Fix for inventory-sharing [SCI-3761]
  app/controllers/repositories_controller.rb
  app/controllers/repository_columns_controller.rb
  app/controllers/repository_rows_controller.rb
  app/models/repository.rb
Labels: features/inventory-improvements, master

#1975 Fix wopi file download URL [SCI-3757]
  app/controllers/wopi_controller.rb
Labels: Active Storage

#1980 Fix template generating [SCI-3767]
  app/services/team_importer.rb
Labels: Active Storage

#1981 Fix protocol import [SCI-3770]
  app/utilities/protocols_importer.rb
Labels: Active Storage

#1982 Share inventory with all teams [SCI-3759]
  app/assets/javascripts/repositories/index.js
  app/controllers/team_repositories_controller.rb
  app/models/repository.rb
  app/permissions/repository.rb
  app/services/repositories/multiple_share_update_service.rb
  app/views/repositories/_share_repository_modal.html.erb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
  app/views/shared/_left_menu_bar.html.erb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  db/migrate/20190812065432_add_share_flag_to_repository.rb
  db/migrate/20190812072649_add_indexes_to_sharing_columns.rb
  db/schema.rb
  spec/factories/repositories.rb
  spec/permissions/repositroy_permissions_spec.rb
  spec/services/repositories/multiple_share_update_service_spec.rb
Labels: features/inventory-improvements, master

#1987 Fix assign/unassign buttons [SCI-3785]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
Labels: features/inventory-improvements

#1988 Fix global search for inventories [SCI-3782]
  app/controllers/repositories_controller.rb
  app/models/repository.rb
Labels: features/inventory-improvements

#1989 Small ux changes for inventories [SCI-3762]
  app/assets/javascripts/repositories/repository_datatable.js.erb
  app/assets/stylesheets/themes/main_navigation.scss
  config/locales/en.yml
Labels: features/inventory-improvements

#1990 Fix translation for view only permission [SCI-3756]
  config/locales/en.yml
Labels: features/inventory-improvements, master

#1991 Add inline editing for inventories [SCI-3763]
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/repositories_controller.rb
  app/views/repositories/show.html.erb
  config/locales/en.yml
Labels: features/inventory-improvements

#1993 Fix shared inventory in task dropdown [SCI-3789]
  app/controllers/my_modules_controller.rb
  app/views/my_modules/_repositories_dropdown.html.erb
Labels: features/inventory-improvements

#1992 Fix error in inventories for new teams [SCI-3788]
  app/assets/javascripts/repositories/index.js
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/index.html.erb
Labels: features/inventory-improvements

#1994 Remove rename button from dropdown [SCI-3763]
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#1995 Merge release-1.16.8 into master
  VERSION
  app/controllers/users/invitations_controller.rb
Labels: master

#1996 Add shared inventory icon [SCI-3783]
  app/helpers/icons_helper.rb
  app/models/repository.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
Labels: master

#2001 Add new permission check for share button [SCI-3794]
  app/controllers/repositories_controller.rb
  app/controllers/team_repositories_controller.rb
  app/permissions/repository.rb
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#1998 Fix UX for task inventory dropdown and big task title [SCI-3791]
  app/assets/stylesheets/partials/_inline_editing.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/my_modules/_repositories_dropdown.html.erb
  app/views/shared/_secondary_navigation.html.erb
Labels: features/inventory-improvements

#1984 Fix steps description and table saving [SCI-3776]
  app/assets/javascripts/protocols/steps.js.erb
Labels: Active Storage

#1985 Fix marvinjs edit button in result and icon [SCI-3774]
  app/assets/stylesheets/marvinjs.scss
  app/models/result.rb
  app/views/my_modules/_result.html.erb
  spec/controllers/result_assets_controller_spec.rb
  spec/services/experiments/generate_workflow_image_service_spec.rb
Labels: Active Storage

#1997 Fix inventory rows import [SCI-3790]
  app/controllers/repositories_controller.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#2003 Remove legacy projects archive HTML views
  app/controllers/projects_controller.rb
  app/views/projects/archive.html.erb
  app/views/projects/archive/_project.html.erb
  app/views/projects/archive/_team_projects.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/projects_controller_spec.rb
Labels: master

#2002 Add assigned items from shared inventories to report [SCI-3792]
  app/controllers/reports_controller.rb
  app/views/reports/new/modal/_module_contents_inner.html.erb
Labels: features/inventory-improvements

#2005 Hide share button for users with one team [SCI-3795]
  app/controllers/repositories_controller.rb
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#2010 Add a team name to inventory item card [SCI-3805]
  app/assets/stylesheets/repositories.scss
  app/views/repositories/_repository_row_info_modal.html.erb
Labels: features/inventory-improvements

#2013 SCI-3806 Add an icon indicating shared status to dropdown
  app/assets/stylesheets/repositories.scss
  app/helpers/inventories_helper.rb
  app/models/repository.rb
  app/views/my_modules/_repositories_dropdown.html.erb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/show.html.erb
  config/locales/en.yml
Labels: features/inventory-improvements

#2016 Fix copy inventory permission [SCI-3810]
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#2017 Create copy permission [SCI-3810]
  app/controllers/repositories_controller.rb
  app/views/repositories/show.html.erb
Labels: features/inventory-improvements

#2018 Update share modal window [SCI-3812]
  app/assets/javascripts/repositories/index.js
  app/assets/stylesheets/extend/bootstrap.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/shared/checkbox.scss
  app/views/repositories/_share_repository_modal.html.erb
  config/locales/en.yml
Labels: features/inventory-improvements
