Repository scinote-eln/scinote-web, pull requests merged in 2020-08, with the labels that each got.

#2750 Add modal for status flow [SCI-4835]
  app/assets/javascripts/my_modules/status_flow.js
  app/assets/stylesheets/my_modules/status_flow.scss
  app/controllers/my_module_status_flow_controller.rb
  app/models/my_module_status.rb
  app/views/my_modules/modals/_status_flow_modal.html.erb
  app/views/my_modules/modals/_status_flow_modal_body.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/status_flow/_task_flow_button.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/routes.rb
Labels: features/task-flows

#2755 Add new statuses to reports [SCI-4837]
  app/assets/stylesheets/reports.scss
  app/helpers/reports_helper.rb
  app/services/reports/docx/draw_my_module.rb
  app/views/reports/elements/_my_module_element.html.erb
  config/locales/en.yml
Labels: features/task-flows

#2791 Fix Collapse and expand buttons position [SCI-4928]
  app/assets/stylesheets/my_modules/results/index.scss
  app/views/my_modules/results.html.erb
Labels: NextRelease

#2797 Fix css for modal-body [SCI-4863]
  app/assets/stylesheets/themes/scinote.scss
Labels: features/task-flows

#2780 Add new statuses to dashboard [SCI-4856]
  app/assets/javascripts/dashboard/current_tasks.js
  app/assets/stylesheets/dashboard/current_tasks.scss
  app/controllers/dashboard/current_tasks_controller.rb
  app/models/my_module.rb
  app/views/dashboards/_current_tasks.html.erb
  config/locales/dashboard/en.yml
Labels: features/task-flows

#2799 Set stateDuration to 0 [SCI-4945]
  app/assets/javascripts/my_modules/repositories.js
  app/assets/javascripts/repositories/repository_datatable.js
Labels: hotfix

#2786 Fix dropdrown selector [SCI-4899]
  app/assets/javascripts/sitewide/dropdown_selector.js
  app/views/dashboards/_current_tasks.html.erb
Labels: features/task-flows

#2790 Add consequence for repository snapshotting [SCI-4866]
  app/models/my_module_status_consequences/repository_snapshot.rb
Labels: features/task-flows

#2795 Default flow, added to seed [SCI-4932]
  app/models/my_module_status_flow.rb
  config/initializers/extends.rb
  db/seeds.rb
  spec/models/my_module_status_flow_spec.rb
Labels: features/task-flows

#2802 Add WOPI preview for office files [SCI-4930]
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/assets_controller.rb
  app/utilities/wopi_util.rb
Labels: features/office-file-previews

#2807 Add migration for task states [SCI-4962]
  app/assets/javascripts/dashboard/current_tasks.js
  app/assets/javascripts/sitewide/dropdown_selector.js
  app/controllers/dashboard/current_tasks_controller.rb
  config/locales/dashboard/en.yml
  db/migrate/20200826143431_migrate_task_status.rb
  db/structure.sql
Labels: features/task-flows

#2774 Add task status to export all [SCI-4829]
  app/models/my_module.rb
  app/services/model_exporters/experiment_exporter.rb
  app/services/team_importer.rb
  app/services/user_data_deletion.rb
Labels: features/task-flows

#2796 Add factories for new task flows models [SCI-4934]
  spec/controllers/my_modules_controller_spec.rb
  spec/factories/my_module_status_conditions.rb
  spec/factories/my_module_status_consequences.rb
  spec/factories/my_module_status_flows.rb
  spec/factories/my_module_status_implications.rb
  spec/factories/my_module_statuses.rb
  spec/factories/my_modules.rb
Labels: features/task-flows
