Repository scinote-eln/scinote-web, pull requests merged in 2020-06, with the labels that each got.

#2628 Change selected line thickness [SCI-4699]
  app/assets/stylesheets/my_modules/repositories.scss
Labels: priority

#2630 Add repositories list view [SCI-4677]
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/repositories/show.js
  app/assets/stylesheets/shared/content_pane.scss
  app/assets/stylesheets/shared/datatable.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/repositories_controller.rb
  app/helpers/repositories_datatable_helper.rb
  app/views/repositories/index.html.erb
  app/views/repositories/show.html.erb
  config/locales/en.yml
  spec/controllers/repositories_controller_spec.rb
Labels: features/inventory-archiving

#2643 Add archive to repository [SCI-4684]
  app/models/repository_base.rb
  app/models/user.rb
  db/migrate/20200603125407_add_archive_to_repository.rb
  db/structure.sql
Labels: features/inventory-archiving

#2636 Add switch for active/archive repository view [SCI-4681][SCI-4682]
  app/assets/javascripts/repositories/index.js
  app/assets/stylesheets/repository/index.scss
  app/assets/stylesheets/shared/content_pane.scss
  app/controllers/repositories_controller.rb
  app/helpers/repositories_datatable_helper.rb
  app/models/repository_base.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/_sidebar_list.html.erb
  app/views/repositories/index.html.erb
  app/views/shared/_view_switch.html.erb
  config/locales/en.yml
  config/routes.rb
  db/structure.sql
  spec/controllers/repositories_controller_spec.rb
Labels: features/inventory-archiving

#2645 Add archive to repository rows [SCI-4689]
  app/models/repository_row.rb
  app/models/user.rb
  db/migrate/20200604210943_add_archive_to_repository_row.rb
  db/structure.sql
Labels: features/inventory-archiving

#2650 Add checkbox selector to DataTable [SCI-4739]
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/sitewide/datatable_helpers.js
  app/helpers/repositories_datatable_helper.rb
  app/views/repositories/index.html.erb
  spec/controllers/repositories_controller_spec.rb
Labels: features/inventory-archiving

#2651 Archiving & restoring rows [SCI-4706]
  app/assets/javascripts/repositories/repository_datatable.js
  app/controllers/repository_rows_controller.rb
  app/models/concerns/archivable_model.rb
  app/models/repository_row.rb
  app/models/user.rb
  app/services/repository_actions/archive_rows_base_service.rb
  app/services/repository_actions/archive_rows_service.rb
  app/services/repository_actions/restore_rows_service.rb
  app/views/repositories/_repository_table.html.erb
  app/views/repositories/_toolbar_buttons.html.erb
  config/initializers/extends.rb
  config/locales/en.yml
  config/locales/global_activities/en.yml
  config/routes.rb
  db/migrate/20200603125407_add_archive_to_repository.rb
  db/migrate/20200604210943_add_archive_to_repository_row.rb
  db/structure.sql
  spec/controllers/repository_rows_controller_spec.rb
  spec/factories/repository_rows.rb
  spec/services/repository_actions/archive_rows_service_spec.rb
  spec/services/repository_actions/restore_rows_service_spec.rb
Labels: features/inventory-archiving

#2662 Fix MarvinJS modal header [SCI-4770] - HotFix
  app/assets/stylesheets/marvinjs.scss
  app/views/shared/_marvinjs_modal.html.erb
Labels: hotfix

#2652 Add archived tags to assigned repository rows [SCI-4703]
  app/assets/javascripts/my_modules/repositories.js
  app/assets/stylesheets/shared/datatable.scss
  app/helpers/repository_datatable_helper.rb
  app/models/my_module.rb
  app/services/reports/docx/repository_helper.rb
Labels: features/inventory-archiving

#2661 Update default scope [SCI-4740] [SCI-4687][SCI-4746]
  app/controllers/my_module_repositories_controller.rb
  app/controllers/repositories_controller.rb
  app/controllers/repository_rows_controller.rb
  app/helpers/reports_helper.rb
  app/models/activity.rb
  app/models/repository.rb
  app/models/repository_snapshot.rb
  app/services/smart_annotations/html_preview.rb
  app/utilities/smart_annotation.rb
  app/views/reports/new/modal/_module_contents_inner.html.erb
  spec/factories/repositories.rb
  spec/models/repository_spec.rb
Labels: features/inventory-archiving

#2665 Switching between the active and archived view in inventory [SCI-4690]
  app/assets/javascripts/repositories/my_module_repository.js
  app/assets/javascripts/repositories/repository_datatable.js
  app/assets/javascripts/repositories/show.js
  app/assets/javascripts/shared/inline_editing.js
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/repository/repository_table.scss
  app/assets/stylesheets/shared/datatable.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/controllers/repositories_controller.rb
  app/controllers/repository_rows_controller.rb
  app/models/repository.rb
  app/views/my_modules/repository.html.erb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/_toolbar_buttons.html.erb
  app/views/repositories/index.html.erb
  app/views/repositories/show.html.erb
  app/views/shared/_view_switch.html.erb
  config/locales/en.yml
Labels: features/inventory-archiving

#2672 Add action buttons to repository index [SCI-4778]
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/sitewide/datatable_helpers.js
  app/controllers/repositories_controller.rb
  app/helpers/repositories_datatable_helper.rb
  app/views/repositories/index.html.erb
  spec/controllers/repositories_controller_spec.rb
Labels: features/inventory-archiving

#2676 Revert default_scope for active repositories [SCI-4786]
  app/controllers/at_who_controller.rb
  app/controllers/my_module_repositories_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/repositories_controller.rb
  app/controllers/repository_rows_controller.rb
  app/helpers/reports_helper.rb
  app/models/activity.rb
  app/models/repository.rb
  app/models/repository_snapshot.rb
  app/services/dashboard/recent_work_service.rb
  app/services/repositories/archive_repository_service.rb
  app/services/repositories/restore_repository_service.rb
  app/views/reports/new/modal/_module_contents_inner.html.erb
  spec/models/repository_spec.rb
Labels: features/inventory-archiving

#2674 Add archived_by and archived_on column to columns manage modal [SCI-4784]
  app/assets/javascripts/repositories/repository_datatable.js
  app/assets/javascripts/repositories/show.js
  app/assets/javascripts/repository_columns/index.js
  app/assets/stylesheets/repository_columns/index.scss
  app/views/repositories/_repository_table.html.erb
  app/views/repository_columns/_manage_column_modal.html.erb
  app/views/repository_columns/_manage_column_modal_index.html.erb
Labels: features/inventory-archiving

#2677 Add migration for repository states [SCI-4783]
  db/migrate/20200622155632_repository_table_state_update.rb
  db/structure.sql
Labels: features/inventory-archiving

#2682 Update my module repositories dropdown list [SCI-4743]
  app/assets/javascripts/repositories/index.js
  app/controllers/my_module_repositories_controller.rb
  app/views/my_modules/repositories/_repositories_dropdown_list.html.erb
Labels: features/inventory-archiving

#2678 Update all rows on repository archive/restore [SCI-4787]
  app/controllers/repository_rows_controller.rb
  app/models/repository_row.rb
  app/services/repositories/archive_repository_service.rb
  app/services/repositories/restore_repository_service.rb
  spec/controllers/repository_rows_controller_spec.rb
  spec/factories/repository_rows.rb
  spec/models/repository_row_spec.rb
  spec/services/repositories/archive_repository_service_spec.rb
  spec/services/repositories/restore_repository_service_spec.rb
Labels: features/inventory-archiving

#2679 Filter out non active repositories and rows [SCI-4741]
  app/controllers/api/v1/inventories_controller.rb
  app/controllers/api/v1/inventory_items_controller.rb
  spec/requests/api/v1/inventories_controller_spec.rb
  spec/requests/api/v1/inventory_items_controller_spec.rb
Labels: features/inventory-archiving

#2683 Hide archived and not assigned items … [SCI-4742]
  app/services/repository_datatable_service.rb
  app/services/repository_rows/my_module_assign_unassign_service.rb
Labels: features/inventory-archiving

#2684 Disable checkbox for shared inventories [SCI-4781]
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/sitewide/datatable_helpers.js
  app/assets/stylesheets/shared/datatable.scss
  app/helpers/repositories_datatable_helper.rb
  config/locales/en.yml
Labels: features/inventory-archiving

#2687 Add tables to TinyMce and small table improvements [SCI-4775]
  app/assets/javascripts/sitewide/tiny_mce.js
  app/assets/stylesheets/hooks/tinymce.scss
  app/assets/stylesheets/tiny_mce.scss
  config/initializers/constants.rb
Labels: features/tinymce-tables

#2692 Add enable 2fa button to user settings [SCI-4754]
  app/assets/javascripts/users/registrations/edit.js
  app/views/users/registrations/_2fa_modal.html.erb
  app/views/users/registrations/edit.html.erb
  config/locales/en.yml
Labels: features/2fa
