Repository scinote-eln/scinote-web, pull requests merged in 2020-11, with the labels that each got.

#2887 Change Complete step button on task step [SCI-5033]
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/steps_controller.rb
  app/views/steps/_step.html.erb
  config/locales/en.yml
Labels: priority

#2928 Create database structure for project folders [SCI-5126]
  app/models/project.rb
  app/models/project_folder.rb
  app/models/team.rb
  db/migrate/20201028103608_create_project_folders.rb
  db/structure.sql
  spec/factories/project_folders.rb
  spec/models/project_folder_spec.rb
Labels: features/folders📁

#2925 Add filer previews to reports [SCI-5110]
  app/assets/stylesheets/reports.scss
  app/assets/stylesheets/reports_print.scss
  app/helpers/reports_helper.rb
  app/services/reports/docx/draw_result_asset.rb
  app/services/reports/docx/draw_step_asset.rb
  app/services/reports/docx_renderer.rb
  app/services/reports/html_to_word_converter.rb
  app/services/reports/utils.rb
  app/views/reports/elements/_my_module_result_asset_element.html.erb
  app/views/reports/elements/_step_asset_element.html.erb
Labels: features/office-file-previews

#2932 Add attachments dropdown to step [SCI-5101]
  app/assets/images/icon_small/marvinjs.svg
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/stylesheets/marvinjs.scss
  app/assets/stylesheets/my_modules.scss
  app/assets/stylesheets/my_modules/results/index.scss
  app/assets/stylesheets/shared_styles/elements/buttons.scss
  app/assets/stylesheets/steps.scss
  app/controllers/steps_controller.rb
  app/views/assets/marvinjs/_create_marvin_sketch_button.html.erb
  app/views/assets/marvinjs/_create_marvin_sketch_li.html.erb
  app/views/assets/wopi/_create_wopi_file_button.html.erb
  app/views/steps/attachments/_list.html.erb
  config/locales/en.yml
Labels: features/office-file-previews

#2936 Add context menu to attachments [SCI-5102]
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/assets.js
  app/assets/stylesheets/shared/assets.scss
  app/assets/stylesheets/shared/file_preview.scss
  app/assets/stylesheets/steps.scss
  app/controllers/assets_controller.rb
  app/controllers/marvin_js_assets_controller.rb
  app/helpers/application_helper.rb
  app/views/assets/_asset.html.erb
  app/views/assets/_asset_context_menu.html.erb
  app/views/assets/_asset_inline.html.erb
  app/views/assets/_asset_list.html.erb
  app/views/assets/_asset_thumbnail.html.erb
  app/views/my_modules/_result_user_generated.html.erb
  app/views/shared/file_preview/_content.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: features/office-file-previews

#2941 Fix teams query [SCI-5124]
  app/models/repository.rb
Labels: priority

#2934 New cards and list layout [SCI-5130][SCI-5131]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/global_activities.scss
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/protocol_management.scss
  app/assets/stylesheets/shared/dropdown_selector.scss
  app/assets/stylesheets/shared_styles/constants/colors.scss
  app/views/projects/index.html.erb
  app/views/projects/index/_folder_card.html.erb
  app/views/projects/index/_project_card.html.erb
  app/views/projects/index/_team_projects.html.erb
  config/locales/en.yml
Labels: features/folders📁

#2947 Add highlight to report table [SCI-4579]
  app/assets/javascripts/reports/reports_datatable.js.erb
  app/assets/stylesheets/reports.scss
Labels: NextRelease

#2949 Add download link to reports [SCI-5166]
  app/assets/stylesheets/reports.scss
  app/services/reports/docx/draw_result_asset.rb
  app/services/reports/docx/draw_step_asset.rb
  app/views/reports/elements/_my_module_result_asset_element.html.erb
  app/views/reports/elements/_step_asset_element.html.erb
  config/locales/en.yml
Labels: features/office-file-previews

#2951 Fix wopi authorization issues [SCI-5214]
  app/controllers/assets_controller.rb
  app/controllers/wopi_controller.rb
Labels: features/office-file-previews

#2952 Add project folders to team import/export [SCI-5184]
  app/services/model_exporters/team_exporter.rb
  app/services/team_importer.rb
Labels: features/folders📁

#2958 Update title font color for asset dropdown [SCI-5224]
  app/assets/stylesheets/shared/assets.scss
  app/assets/stylesheets/steps.scss
Labels: features/office-file-previews

#2959 Add scinote link to PDF reports [SCI-5225]
  app/views/reports/elements/_experiment_element.html.erb
  app/views/reports/elements/_my_module_element.html.erb
Labels: features/office-file-previews

#2921 Add filters flyout [SCI-5127]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/projects.scss
  app/views/projects/index/_toolbar.html.erb
  config/locales/en.yml
Labels: features/folders📁

#2969 Remove complete step button from protocol step… [SCI-5236]
  app/assets/stylesheets/steps.scss
  app/views/steps/_step.html.erb
Labels: NextRelease

#2972 Replace loading spinner [SCI-5229]
  app/assets/javascripts/application.js.erb
  app/assets/stylesheets/shared/assets.scss
  app/assets/stylesheets/shared/file_preview.scss
  app/assets/stylesheets/themes/scinote.scss
  public/images/medium/loading.svg
  public/images/medium/loading_white.svg
Labels: NextRelease

#2963 Add comments sidebar layout [SCI-5186][SCI-5188][SCI-5189]
  app/assets/images/comments/placeholder.svg
  app/assets/javascripts/sitewide/comments_sidebar.js
  app/assets/stylesheets/shared/comments_sidebar.scss
  app/assets/stylesheets/shared_styles/constants/transition.scss
  app/controllers/comments_controller.rb
  app/controllers/my_module_comments_controller.rb
  app/controllers/project_comments_controller.rb
  app/controllers/result_comments_controller.rb
  app/controllers/step_comments_controller.rb
  app/helpers/comment_helper.rb
  app/models/my_module.rb
  app/models/project.rb
  app/models/project_comment.rb
  app/models/result.rb
  app/models/result_comment.rb
  app/models/step.rb
  app/models/step_comment.rb
  app/models/task_comment.rb
  app/views/layouts/application.html.erb
  app/views/shared/comments/_comment.html.erb
  app/views/shared/comments/_comments_list.html.erb
  app/views/shared/comments/_comments_sidebar.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: features/folders📁

#2974 Add new icons for assets [SCI-5230]
  app/assets/images/icon_small/docx_file.svg
  app/assets/images/icon_small/marvinjs_file.svg
  app/assets/images/icon_small/pptx_file.svg
  app/assets/images/icon_small/xslx_file.svg
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/shared/assets.scss
  app/assets/stylesheets/shared_styles/constants/colors.scss
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/file_icons_helper.rb
  app/views/assets/_asset_list.html.erb
Labels: NextRelease

#2977 Implement ESC button to exit full-screen modals [SCI-5048]
  app/assets/javascripts/my_modules/repositories.js
  app/assets/javascripts/sitewide/image_editor.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/views/my_modules/protocols.html.erb
  app/views/shared/_file_preview_modal.html.erb
  app/views/shared/file_preview/_modal.html.erb
Labels: NextRelease

#2979 Add new SciNote avatars [SCI-5234]
  app/views/users/registrations/edit.html.erb
  public/images/avatars/17.png
  public/images/avatars/18.png
  public/images/avatars/19.png
  public/images/avatars/20.png
  public/images/avatars/21.png
  public/images/avatars/22.png
  public/images/avatars/23.png
  public/images/avatars/24.png
  public/images/avatars/25.png
  public/images/avatars/26.png
  public/images/avatars/27.png
  public/images/avatars/28.png
Labels: NextRelease

#2960 Fix assets sorting in report [SCI-5228]
  app/controllers/concerns/report_actions.rb
  app/models/asset.rb
  app/models/step.rb
Labels: NextRelease

#2981 Small file preview css fixes [SCI-5242]
  app/assets/stylesheets/my_modules/results/index.scss
  app/assets/stylesheets/shared/assets.scss
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/helpers/file_icons_helper.rb
  app/views/assets/wopi/_file_wopi_controls.html.erb
  app/views/my_modules/_result.html.erb
  config/locales/en.yml
Labels: NextRelease

#2980 Add delete asset confirmation modal [SCI-5241]
  app/assets/javascripts/sitewide/assets.js
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/stylesheets/shared/file_preview.scss
  app/assets/stylesheets/steps.scss
  app/controllers/assets_controller.rb
  app/helpers/file_icons_helper.rb
  app/models/asset.rb
  app/views/assets/_asset_context_menu.html.erb
  app/views/assets/_asset_delete_modal.html.erb
  app/views/assets/_asset_inline.html.erb
  app/views/assets/_asset_list.html.erb
  app/views/assets/_asset_thumbnail.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/protocols/edit.html.erb
  app/views/shared/_file_preview_icon.html.erb
  app/views/shared/_file_preview_modal.html.erb
  app/views/shared/file_preview/_content.html.erb
  app/views/shared/file_preview/_modal.html.erb
  app/views/steps/attachments/_list.html.erb
  config/locales/en.yml
Labels: NextRelease

#2954 Add activity for project moving [SCI-5182]
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
Labels: features/folders📁

#2986 Add h6 render to docx report [SCI-5256]
  app/services/reports/html_to_word_converter.rb
Labels: NextRelease

#2985 Add preview files to export all [SCI-5250]
  app/helpers/reports_helper.rb
  app/models/team_zip_export.rb
  app/views/reports/elements/_my_module_repository_element.html.erb
  app/views/reports/elements/_my_module_result_asset_element.html.erb
  app/views/reports/elements/_my_module_result_table_element.html.erb
  app/views/reports/elements/_step_asset_element.html.erb
  app/views/reports/elements/_step_table_element.html.erb
Labels: NextRelease
