Repository scinote-eln/scinote-web, pull requests merged in 2020-07, with the labels that each got.

#2696 Add 2FA to login flow [SCI-4753]
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/views/users/sessions/new.html.erb
  app/views/users/sessions/two_factor_auth.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/models/user_spec.rb
Labels: features/2fa

#2697 Add 2fa to user settings page [SCI-4755]
  Gemfile
  Gemfile.lock
  app/assets/javascripts/users/registrations/edit.js
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/views/users/registrations/_2fa_modal.html.erb
  app/views/users/registrations/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/models/user_spec.rb
Labels: features/2fa

#2698 Disable column reordering in repositories list [SCI-4807]
  app/assets/javascripts/repositories/index.js
Labels: features/inventory-archiving

#2701 Add empty states to inventories datatable and fix filtering bug [SCI-4793]
  app/assets/javascripts/repositories/index.js
  app/assets/javascripts/repositories/repository_datatable.js
  app/services/repository_datatable_service.rb
  config/initializers/constants.rb
  config/locales/en.yml
  spec/support/matchers/be_valid_default_repository_state.rb
  spec/support/matchers/be_valid_repository_table_state.rb
Labels: features/inventory-archiving

#2708 merge cucumbers [SCI-4798]
  .rubocop.yml
  Moon.png
  app/controllers/api/v1/results_controller.rb
  app/views/projects/index.html.erb
  app/views/result_assets/_edit.html.erb
  app/views/result_assets/_new.html.erb
  app/views/result_tables/_edit.html.erb
  app/views/result_tables/_new.html.erb
  app/views/result_texts/_edit.html.erb
  app/views/result_texts/_new.html.erb
  app/views/steps/_new.html.erb
  app/views/users/passwords/edit.html.erb
  app/views/users/passwords/new.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  features/home_page.feature
  features/home_page.feature.pending
  features/invite_user.feature
  features/invite_user.feature.pending
  features/project.feature
  features/project.feature.pending
  features/projects_page/project_archiving.feature
  features/projects_page/project_comments.feature
  features/projects_page/project_managing.feature
  features/projects_page/project_users.feature
  features/protocol.feature
  features/protocol.feature.pending
  features/protocol_step.feature
  features/result.feature
  features/sessions/forgot_password.feature
  features/sessions/log_in.feature
  features/sessions/sign_up.feature
  features/settings_page/profile.feature
  features/settings_page/team.feature
  features/step_definitions/invite_user_steps.rb
  features/step_definitions/navigation_steps.rb
  features/step_definitions/profile_steps.rb
  features/step_definitions/project_steps.rb
  features/step_definitions/projects_page_steps.rb
  features/step_definitions/protocol_steps.rb
  features/step_definitions/result_steps.rb
  features/step_definitions/shared_steps.rb
  features/step_definitions/team_steps.rb
  features/step_definitions/users_steps.rb
  features/support/env.rb
  features/support/shared_methods.rb
  features/teams.feature
  features/teams.feature.pending
  spec/requests/api/v1/results_controller_spec.rb
Labels: features/cucumbers 🥒

#2725 Disable inventories table initialization on turbolinks preview [SCI-4820]
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/repositories/index.js
Labels: NextRelease

#2726 Remove search state load from repositories table [SCI-4855]
  app/assets/javascripts/my_modules/repositories.js
Labels: NextRelease

#2731 Fix Settings pages titles [SCI-4567]
  app/assets/stylesheets/global_activities.scss
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/settings/addons.scss
  app/assets/stylesheets/settings/connected_accounts.scss
  app/assets/stylesheets/settings/preferences.scss
  app/assets/stylesheets/shared/content_pane.scss
  app/assets/stylesheets/steps.scss
  app/views/steps/_step.html.erb
  app/views/users/settings/account/addons/index.html.erb
  app/views/users/settings/account/connected_accounts/index.html.erb
  app/views/users/settings/account/preferences/index.html.erb
  config/locales/en.yml
Labels: NextRelease

#2713 Add UX design to 2FA settings page [SCI-4814]
  app/assets/images/2fa/2fa_authenticator.png
  app/assets/images/2fa/google_authenticator.png
  app/assets/images/2fa/install_mobile.png
  app/assets/images/2fa/ms_authenticator.png
  app/assets/javascripts/users/registrations/edit.js
  app/assets/stylesheets/settings/users.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/users/registrations_controller.rb
  app/javascript/packs/fontawesome.scss
  app/views/users/registrations/_2fa_modal.html.erb
  app/views/users/registrations/_2fa_modal_apps_tab.html.erb
  app/views/users/registrations/_2fa_modal_qr_code_tab.html.erb
  app/views/users/registrations/_2fa_modal_verify_code_tab.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/edit_partials/_2fa.html.erb
  app/views/users/registrations/edit_partials/_avatar.html.erb
  app/views/users/registrations/edit_partials/_email.html.erb
  app/views/users/registrations/edit_partials/_full_name.html.erb
  app/views/users/registrations/edit_partials/_initials.html.erb
  app/views/users/registrations/edit_partials/_password.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  features/settings_page/profile.feature
Labels: features/2fa

#2730 Improve pdf reports [SCI-4874]
  app/assets/stylesheets/reports.scss
  app/assets/stylesheets/reports_print.scss
  app/helpers/reports_helper.rb
  app/views/reports/footer.pdf.erb
  app/views/reports/header.pdf.erb
  app/views/reports/report.pdf.erb
Labels: NextRelease

#2740 Implement Status labels on a Task card [SCI-4823]
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/canvas/full_zoom/_my_module.html.erb
Labels: features/task-flows

#2735 New task flow buttons and actions [SCI-4824] [SCI-4833]
  app/assets/javascripts/my_modules.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/my_modules/status_flow.scss
  app/assets/stylesheets/shared_styles/elements/dropdown.scss
  app/controllers/my_modules_controller.rb
  app/models/my_module_status.rb
  app/models/my_module_status_flow.rb
  app/permissions/experiment.rb
  app/permissions/my_module.rb
  app/views/my_modules/_complete_task_modal.html.erb
  app/views/my_modules/_module_state_label.html.erb
  app/views/my_modules/_my_module_details.html.erb
  app/views/my_modules/_state_button_complete.html.erb
  app/views/my_modules/_state_button_uncomplete.html.erb
  app/views/my_modules/_state_buttons.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/my_modules/status_flow/_task_flow_button.html.erb
  config/locales/en.yml
  config/locales/my_module_statuses/en.yml
  config/routes.rb
  features/protocol.feature
  spec/controllers/my_modules_controller_spec.rb
Labels: features/task-flows

#2714 Enable Content Security Policy [SCI-4796]
  config/initializers/content_security_policy.rb
Labels: features/security-improvements
