Repository scinote-eln/scinote-web, pull requests merged in 2020-10, with the labels that each got.

#2879 Refactor WOPI discovery [SCI-4957]
  app/controllers/wopi_controller.rb
  app/models/asset.rb
  app/models/wopi_action.rb
  app/models/wopi_discovery.rb
  app/utilities/wopi_util.rb
Labels: features/office-file-previews

#2809 Render wopi preview only in view port
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/drag_n_drop.js
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/assets_controller.rb
  app/controllers/marvin_js_assets_controller.rb
  app/models/asset.rb
  app/views/assets/_asset.html.erb
  app/views/assets/_asset_inline.html.erb
  app/views/assets/_asset_link.html.erb
  app/views/assets/_asset_thumbnail.html.erb
  app/views/assets/_new_asset.html.erb
  app/views/my_modules/_result_user_generated.html.erb
  app/views/shared/_asset_placeholder.html.erb
  app/views/steps/_empty_step.html.erb
  app/views/steps/attachments/_edit_item.html.erb
  app/views/steps/attachments/_item.html.erb
  app/views/steps/attachments/_list.html.erb
  spec/controllers/assets_controller_spec.rb
Labels: features/office-file-previews

#2898 Move snapshot default selection from addon to core [SCI-5071]
  app/models/my_module_status_consequences/repository_snapshot.rb
Labels: NextRelease, priority

#2902 Add 'Open in APP' button to the task
  app/assets/javascripts/my_modules/pwa_mobile_app.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/shared_styles/elements/buttons.scss
  app/helpers/pwa_helper.rb
  app/models/protocol.rb
  app/views/my_modules/_open_mobile_app.html.erb
  app/views/my_modules/protocols.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/assets.rb
  config/initializers/constants.rb
  config/locales/en.yml
Labels: NextRelease

#2908 Fix pwa url and change when banner is displayed [SCI-5120]
  app/assets/javascripts/my_modules/pwa_mobile_app.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/helpers/pwa_helper.rb
  app/models/protocol.rb
  app/views/my_modules/_open_mobile_app.html.erb
  config/initializers/constants.rb
Labels: NextRelease

#2917 Move open mobile app button to main navigation [SCI-5119]
  app/assets/javascripts/my_modules/pwa_mobile_app.js
  app/assets/stylesheets/my_modules/protocols/index.scss
  app/assets/stylesheets/shared_styles/elements/buttons.scss
  app/assets/stylesheets/themes/main_navigation.scss
  app/views/my_modules/_open_mobile_app.html.erb
  app/views/my_modules/protocols.html.erb
  app/views/shared/_navigation.html.erb
  config/locales/en.yml
  public/images/sn-icon.svg
Labels: NextRelease

#2900 Add list view to attachments [SCI-5109]
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/stylesheets/steps.scss
  app/models/asset.rb
  app/views/assets/_asset.html.erb
  app/views/assets/_asset_inline.html.erb
  app/views/assets/_asset_list.html.erb
  app/views/assets/_asset_thumbnail.html.erb
  config/locales/en.yml
Labels: features/office-file-previews

#2915 Update image edit modal [SCI-5105]
  app/assets/stylesheets/shared/image_edit_modal.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/shared/_file_edit_modal.html.erb
Labels: features/office-file-previews

#2912 Add current team to smart annotations permission check [SCI-5091]
  app/services/smart_annotations/permission_eval.rb
  spec/services/smart_annotations/permission_eval_spec.rb
Labels: priority

#2901 Refactor experiment workflow image generation [SCI-5063]
  app/assets/javascripts/projects/show.js
  app/assets/stylesheets/projects.scss
  app/controllers/canvas_controller.rb
  app/controllers/experiments_controller.rb
  app/models/experiment.rb
  app/models/my_module.rb
  app/services/create_my_module_service.rb
  app/services/experiments/copy_experiment_as_template_service.rb
  app/services/experiments/generate_workflow_image_service.rb
  app/services/team_importer.rb
  app/utilities/first_time_data_generator.rb
  app/views/projects/show/_experiment.html.erb
  app/views/projects/show/_workflow_img.html.erb
  config/routes.rb
  spec/services/experiments/generate_workflow_image_service_spec.rb
  spec/services/model_importers/team_importer_spec.rb
Labels: priority

#2878 Support multiple file upload in TinyMCE fields [SCI-5040]
  app/assets/javascripts/sitewide/file_utils.js
  app/assets/javascripts/sitewide/tiny_mce_file_upload_plugin.js
  app/controllers/tiny_mce_assets_controller.rb
  app/helpers/bootstrap_form_helper.rb
Labels: priority

#2910 Update file preview [SCI-5103][SCI-5104]
  app/assets/javascripts/my_modules/repositories.js
  app/assets/javascripts/my_modules/results.js
  app/assets/javascripts/protocols/index.js
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/repositories/repository_datatable.js
  app/assets/javascripts/results/result_assets.js
  app/assets/javascripts/sitewide/drag_n_drop.js
  app/assets/javascripts/sitewide/file_preview.js
  app/assets/javascripts/sitewide/image_editor.js
  app/assets/javascripts/sitewide/marvinjs_editor.js
  app/assets/javascripts/sitewide/repository_row_info_modal.js
  app/assets/stylesheets/shared/file_preview.scss
  app/assets/stylesheets/shared_styles/elements/buttons.scss
  app/assets/stylesheets/steps.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/assets_controller.rb
  app/permissions/asset.rb
  app/views/assets/_asset.html.erb
  app/views/assets/_asset_inline.html.erb
  app/views/assets/_asset_list.html.erb
  app/views/assets/_asset_thumbnail.html.erb
  app/views/assets/wopi/_file_wopi_controls.html.erb
  app/views/layouts/application.html.erb
  app/views/my_modules/archive.html.erb
  app/views/repositories/_repository_row_info_modal.html.erb
  app/views/shared/file_preview/_content.html.erb
  app/views/shared/file_preview/_file_icon.html.erb
  app/views/shared/file_preview/_modal.html.erb
  app/views/steps/attachments/_list.html.erb
  config/locales/en.yml
Labels: features/office-file-previews

#2918 Refactor projects page [SCI-5134]
  app/controllers/projects_controller.rb
  app/views/projects/_new.html.erb
  app/views/projects/index.html.erb
  app/views/projects/index/_toolbar.html.erb
  app/views/projects/index/modals/_edit.html.erb
  app/views/projects/index/modals/_export_projects.html.erb
  app/views/projects/index/modals/_manage_users.html.erb
  app/views/projects/index/modals/_new.html.erb
  config/routes.rb
  spec/controllers/projects_controller_spec.rb
Labels: features/folders📁

#2922 Add asset preview mode switcher to step [SCI-5107]
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/sitewide/assets.js
  app/assets/javascripts/sitewide/drag_n_drop.js
  app/controllers/assets_controller.rb
  app/controllers/steps_controller.rb
  app/models/step.rb
  app/views/steps/attachments/_list.html.erb
  config/routes.rb
  db/migrate/20201027133634_add_assets_view_mode_to_step.rb
  db/structure.sql
Labels: features/office-file-previews
