Repository scinote-eln/scinote-web, pull requests merged in 2020-01, with the labels that each got.

#2278 Add search for statuses, numbers [SCI-4161]
  app/models/concerns/searchable_model.rb
  app/models/repository_number_value.rb
  app/views/search/results/_repositories.html.erb
  config/initializers/extends.rb
Labels: features/new-column-types

#2264 Add helper for repository tables in docx report [SCI-4157]
  app/models/repository_checklist_value.rb
  app/services/reports/docx.rb
  app/services/reports/docx/draw_my_module_repository.rb
  app/services/reports/docx/repository_helper.rb
Labels: features/new-column-types

#2287 Update validation for repository text field [SCI-4213]
  app/assets/javascripts/repositories/validators/base_validator.js
  app/assets/javascripts/sitewide/constants.js.erb
Labels: features/new-column-types

#2286 Fix for numeric item in SQL array [SCI-4161]
  app/models/concerns/searchable_model.rb
Labels: priority

#2360 DIsable edit/delete buttons for repository item, communicate read-only [SCI-4297] [SCI-4305]
  app/assets/javascripts/repositories/repository_datatable.js
  app/assets/stylesheets/my_modules/repositories.scss
  app/assets/stylesheets/repository/repository_table.scss
  app/helpers/repository_datatable_helper.rb
  app/models/repository_row.rb
  app/services/repository_datatable_service.rb
  config/initializers/extends.rb
  config/locales/en.yml
Labels: NextRelease

#2361 Hide Edit/Delete buttons if user do not has permissions [SCI-4298]
  app/assets/javascripts/repository_columns/index.js
  app/assets/stylesheets/repository_columns/index.scss
  app/views/repositories/_repository_table.html.erb
Labels: NextRelease

#2358 Change to new style checkboxes on share inventory modal [SCI-4275]
  app/assets/javascripts/repositories/index.js
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/shared/checkbox.scss
  app/assets/stylesheets/shared_styles/elements/checkboxes.scss
  app/assets/stylesheets/shared_styles/elements/toggles.scss
  app/views/repositories/_share_repository_modal.html.erb
  app/views/repository_columns/manage_column_partials/_date.html.erb
  app/views/repository_columns/manage_column_partials/_datetime.html.erb
  app/views/repository_columns/manage_column_partials/_time.html.erb
Labels: NextRelease

#2372 Fix repository data time range column width [SCI-4306]
  app/assets/stylesheets/repository/repository_table.scss
Labels: NextRelease
