Repository scinote-eln/scinote-web, pull requests merged in 2020-09, with the labels that each got.

#2769 Add activities for status change [SCI-4827]
  app/controllers/my_modules_controller.rb
  config/initializers/extends.rb
  config/locales/global_activities/en.yml
  spec/controllers/my_modules_controller_spec.rb
Labels: features/task-flows

#2811 Fix edit experiment error [SCI-4967]
  app/views/canvas/edit/_my_module.html.erb
Labels: features/task-flows

#2812 Show status on task card [SCI-4969]
  app/assets/stylesheets/themes/scinote.scss
  app/views/canvas/full_zoom/_my_module.html.erb
Labels: features/task-flows

#2810 Add error handling for state change [SCI-4968]
  app/assets/javascripts/my_modules.js
  app/controllers/my_modules_controller.rb
  app/models/my_module.rb
  config/locales/en.yml
  spec/controllers/my_modules_controller_spec.rb
Labels: features/task-flows

#2826 Skip implications for my_module canvas position update [SCI-4985]
  app/models/my_module.rb
Labels: features/task-flows

#2798 Add API endpoints for workflows [SCI-4831]
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/tasks_controller.rb
  app/controllers/api/v1/workflow_statuses_controller.rb
  app/controllers/api/v1/workflows_controller.rb
  app/serializers/api/v1/task_serializer.rb
  app/serializers/api/v1/workflow_serializer.rb
  app/serializers/api/v1/workflow_status_serializer.rb
  config/routes.rb
  spec/requests/api/v1/tasks_controller_spec.rb
  spec/requests/api/v1/workflow_statuses_controller_spec.rb
  spec/requests/api/v1/workflows_controller_spec.rb
Labels: features/task-flows

#2817 Add completed/uncompleted methods to my_module [SCI-4972]
  app/controllers/dashboard/current_tasks_controller.rb
  app/helpers/my_modules_helper.rb
  app/models/my_module.rb
  app/views/my_modules/_card_due_date_label.html.erb
  app/views/my_modules/_due_date_label.html.erb
  config/locales/dashboard/en.yml
Labels: features/task-flows

#2830 Update smart annotation appearance in the text [SCI-4952]
  app/assets/stylesheets/themes/scinote.scss
  app/services/smart_annotations/html_preview.rb
  spec/services/smart_annotations/html_preview_spec.rb
  spec/services/smart_annotations/tag_to_html_spec.rb
Labels: features/smart-annotation

#2829 Add description for conditions [SCI-4983]
  app/assets/stylesheets/my_modules/status_flow.scss
  app/models/my_module_status_conditions/active.rb
  app/views/my_modules/modals/_status_flow_modal_body.html.erb
  config/locales/my_module_statuses/en.yml
Labels: features/task-flows

#2819 Add front-end checks for statuses [SCI-4975]
  app/assets/stylesheets/my_modules/status_flow.scss
  app/models/my_module_status.rb
  app/views/my_modules/status_flow/_task_flow_button.html.erb
Labels: features/task-flows

#2832 Add error message for locked task, update some permission checks[SCI-4982]
  app/assets/javascripts/my_modules.js
  app/assets/javascripts/my_modules/protocols.js
  app/assets/javascripts/my_modules/repositories.js
  app/assets/javascripts/protocols/steps.js.erb
  app/assets/javascripts/shared/inline_editing.js
  app/assets/javascripts/sitewide/comments.js
  app/assets/javascripts/sitewide/tiny_mce.js
  app/controllers/my_module_tags_controller.rb
  app/controllers/my_modules_controller.rb
  app/controllers/protocols_controller.rb
  app/controllers/steps_controller.rb
  app/controllers/tags_controller.rb
  config/locales/en.yml
  spec/controllers/my_modules_controller_spec.rb
  spec/controllers/protocols_controller_spec.rb
Labels: features/task-flows

#2836 Fix canvas task due date and status alignment [SCI-4992]
  app/views/canvas/full_zoom/_my_module.html.erb
Labels: features/task-flows

#2824 Refactor smart annotation front-end [SCI-4949]
  app/assets/javascripts/sitewide/atwho_res.js.erb
  app/assets/stylesheets/shared/my_modules_list_partial.scss
  app/assets/stylesheets/shared/smart_annotation.scss
  app/assets/stylesheets/shared_styles/elements/bootstrap_tabs.scss
  app/assets/stylesheets/themes/scinote.scss
  app/controllers/at_who_controller.rb
  app/helpers/experiments_helper.rb
  app/utilities/smart_annotation.rb
  app/views/layouts/application.html.erb
  app/views/shared/smart_annotation/_experiment_items.html.erb
  app/views/shared/smart_annotation/_footer.html.erb
  app/views/shared/smart_annotation/_menu.html.erb
  app/views/shared/smart_annotation/_my_module_items.html.erb
  app/views/shared/smart_annotation/_no_results.html.erb
  app/views/shared/smart_annotation/_project_items.html.erb
  app/views/shared/smart_annotation/_repository_items.html.erb
  config/initializers/constants.rb
  config/locales/en.yml
  config/routes.rb
Labels: features/smart-annotation

#2837 Disable button when condition not fulfilled [SCI-4998]
  app/assets/stylesheets/my_modules/status_flow.scss
  app/models/my_module_status.rb
  app/views/my_modules/status_flow/_task_flow_button.html.erb
Labels: features/task-flows

#2846 Fix JS error, empty task
  app/assets/javascripts/my_modules.js
Labels: features/task-flows

#2815 Add view mode field to the Asset model [SCI-4958]
  app/models/asset.rb
  db/migrate/20200902093234_add_view_mode_to_asset.rb
  db/structure.sql
Labels: features/office-file-previews

#2838 Update user smart annotation [SCI-4986][SCI-4995]
  app/assets/javascripts/sitewide/atwho_res.js
  app/assets/javascripts/sitewide/atwho_res.js.erb
  app/assets/stylesheets/shared/smart_annotation.scss
  app/controllers/at_who_controller.rb
  app/utilities/smart_annotation.rb
  app/views/shared/smart_annotation/_experiment_items.html.erb
  app/views/shared/smart_annotation/_menu.html.erb
  app/views/shared/smart_annotation/_my_module_items.html.erb
  app/views/shared/smart_annotation/_no_results.html.erb
  app/views/shared/smart_annotation/_project_items.html.erb
  app/views/shared/smart_annotation/_repository_items.html.erb
  app/views/shared/smart_annotation/_users.html.erb
  config/locales/en.yml
Labels: features/smart-annotation

#2845 Improve search for smart annotations [SCI-4789]
  app/models/concerns/searchable_by_name_model.rb
  app/utilities/smart_annotation.rb
Labels: features/smart-annotation

#2844 Add remembered state for smart annotation [SCI-4950]
  app/assets/javascripts/sitewide/atwho_res.js
  app/assets/stylesheets/shared/smart_annotation.scss
  app/controllers/at_who_controller.rb
  app/views/shared/smart_annotation/_footer.html.erb
  app/views/shared/smart_annotation/_menu.html.erb
Labels: features/smart-annotation

#2856 Update empty states for smart annotation results and dismiss button [SCI-5009]
  app/assets/javascripts/sitewide/atwho_res.js
  app/assets/stylesheets/shared/smart_annotation.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/shared/smart_annotation/_experiment_items.html.erb
  app/views/shared/smart_annotation/_menu.html.erb
  app/views/shared/smart_annotation/_my_module_items.html.erb
  app/views/shared/smart_annotation/_no_results.html.erb
  app/views/shared/smart_annotation/_project_items.html.erb
  app/views/shared/smart_annotation/_repository_items.html.erb
  app/views/shared/smart_annotation/_users.html.erb
  config/locales/en.yml
Labels: features/smart-annotation

#2860 Add info of the locked task to the View status flow modal [SCI-5007]
  app/models/my_module_status_condition.rb
  app/models/my_module_status_implication.rb
  app/views/my_modules/modals/_status_flow_modal_body.html.erb
Labels: features/task-flows

#2868 Fix smart annotation for RepositoryItem [SCI-5057]
  app/services/smart_annotations/html_preview.rb
  app/services/smart_annotations/tag_to_html.rb
Labels: NextRelease

#2871 Fix step deletion [SCI-4849]
  app/controllers/api/v1/assets_controller.rb
  app/controllers/api/v1/results_controller.rb
Labels: NextRelease

#2873 Small smart annotation fixes [SCI-5038]
  app/assets/javascripts/protocols/header.js
  config/initializers/constants.rb
Labels: NextRelease

#2882 Remove complete step button from protocol managment [SCI-5072]
  app/views/steps/_step.html.erb
Labels: NextRelease
