Repository scinote-eln/scinote-web, pull requests merged in 2021-01, with the labels that each got.

#3032 Fix global activities page [SCI-5324]
  app/models/my_module.rb
Labels: features/folders📁

#3025 [SCI-5280] Rename Academy to Courses
  config/locales/en.yml
Labels: NextRelease

#3024 [SCI-5293] Remove Archived results tab on archived Task
  app/views/my_modules/status_flow/_task_flow_button.html.erb
  app/views/shared/_secondary_navigation.html.erb
  app/views/shared/sidebar/_my_module.html.erb
  config/locales/en.yml
Labels: features/folders📁

#3039 Disable comment adding for archived objects [SCI-5339]
  app/assets/javascripts/sitewide/comments_sidebar.js
  app/controllers/comments_controller.rb
  app/helpers/comment_helper.rb
Labels: features/folders📁

#3041 Fix links in sidebar navigation [SCI-5327]
  app/helpers/sidebar_helper.rb
  app/views/shared/sidebar/_archived_my_modules.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_my_modules.html.erb
Labels: features/folders📁

#3013 Fix cursor on SmartAnnotation [SCI-5084]
  app/assets/stylesheets/shared/smart_annotation.scss
Labels: NextRelease

#3014 Add 'archived' to smart annotation for repository item [SCI-5283]
  app/services/smart_annotations/html_preview.rb
  app/views/repositories/_repository_row_info_modal.html.erb
Labels: NextRelease

#3040 Fix project card menu visibility [SCI-5328]
  app/views/projects/index/_project_actions_dropdown.html.erb
Labels: features/folders📁

#3042 Make active projects view default [SCI-5340]
  app/controllers/projects_controller.rb
  app/helpers/projects_helper.rb
  app/models/project.rb
  app/models/team.rb
  app/services/projects_overview_service.rb
  app/views/projects/index/_header.html.erb
  app/views/projects/index/_project.html.erb
  app/views/projects/index/_team_projects_table.html.erb
  app/views/projects/index/_toolbar.html.erb
  app/views/projects/index_dt.json.jbuilder
  app/views/projects/show/_header.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: features/folders📁

#3046 Add default sorting to ProjectsOverviewService [SCI-5361]
  app/services/projects_overview_service.rb
Labels: features/folders📁

#3033 Fix restore action for experiments and tasks [SCI-5341]
  app/assets/javascripts/my_modules/archived.js
  app/controllers/experiments_controller.rb
  app/controllers/my_modules_controller.rb
  app/helpers/application_helper.rb
  app/models/concerns/archivable_model.rb
  app/models/my_module.rb
  app/views/experiments/module_archive.html.erb
  app/views/shared/_flash_alerts.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/experiments_controller_spec.rb
  spec/controllers/my_modules_controller_spec.rb
  spec/factories/my_modules.rb
Labels: features/folders📁

#3038 Fix projects visibility in the sidebar [SCI-5338]
  app/helpers/projects_helper.rb
  app/models/project.rb
  app/models/user.rb
Labels: features/folders📁

#3037 Fix project buttons visibility [SCI-5318]
  app/assets/javascripts/projects/index.js
  app/views/projects/index/_toolbar.html.erb
Labels: features/folders📁

#3045 Tooltip for users on project cards [SCI-5320]
  app/assets/stylesheets/projects.scss
  app/helpers/projects_helper.rb
  app/views/projects/index/_project_card.html.erb
Labels: features/folders📁

#3031 Update repositories sidebar [SCI-5329]
  app/assets/javascripts/repositories/index.js
  app/assets/stylesheets/partials/_sidebar.scss
  app/assets/stylesheets/repositories.scss
  app/controllers/repositories_controller.rb
  app/views/repositories/_sidebar.html.erb
  app/views/repositories/_sidebar_list.html.erb
  app/views/repositories/index.html.erb
  app/views/repositories/show.html.erb
  config/locales/en.yml
Labels: features/folders📁

#3050 Fix table view of project page display of users [SCI-5336]
  app/assets/stylesheets/projects.scss
Labels: features/folders📁

#3043 Fix projects filter mark, titles and comments mark [SCI-5332]
  app/assets/javascripts/projects/index.js
  app/views/projects/index/_folder_card.html.erb
  app/views/projects/index/_project_card.html.erb
  app/views/shared/comments/_comments_list.html.erb
Labels: features/folders📁

#3051 Change buttons style in projects toolbar [SCI-5335]
  app/views/projects/index/_toolbar.html.erb
Labels: features/folders📁

#3055 Fix bug with users edit link not working [SCI-5374]
  app/assets/javascripts/projects/index.js
Labels: features/folders📁

#3054 Add searching to projects member filter [SCI-5373]
  app/controllers/projects_controller.rb
Labels: features/folders📁

#3048 Add projects navigation buttons and fix sidebar reload on sorting [SCI-5357][SCI-5331]
  app/assets/javascripts/projects/index.js
  app/assets/javascripts/sidebar.js
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/helpers/projects_helper.rb
  app/services/projects_overview_service.rb
  app/views/projects/index.html.erb
  app/views/shared/sidebar/_projects.html.erb
  config/locales/en.yml
Labels: features/folders📁

#3053 Update archived experiments navigation [SCI-5346]
  app/views/projects/experiment_archive.html.erb
  app/views/projects/index/_project_card.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_projects_tree_branch.html.erb
  config/locales/en.yml
Labels: features/folders📁

#3049 Small fixes for projects folder cards [SCI-5345]
  app/assets/stylesheets/projects.scss
  app/services/projects_overview_service.rb
  app/views/projects/index/_folder_card.html.erb
Labels: features/folders📁

#3052 Update archive navigation for tasks page [SCI-5347]
  app/controllers/experiments_controller.rb
  app/views/experiments/module_archive.html.erb
  app/views/projects/show/_experiment.html.erb
  app/views/shared/sidebar/_experiments.html.erb
  app/views/shared/sidebar/_my_modules.html.erb
  config/locales/en.yml
Labels: features/folders📁

#3058 Folder name uniqueness validation on folder level and renaming [SCI-5312]
  app/assets/javascripts/projects/index.js
  app/models/project_folder.rb
  spec/models/project_folder_spec.rb
Labels: features/folders📁

#3063 Fix comments counter [SCI-5371]
  app/assets/javascripts/sitewide/comments_sidebar.js
  app/controllers/comments_controller.rb
  app/helpers/comment_helper.rb
  app/views/projects/index/_project_actions_dropdown.html.erb
Labels: NextRelease

#3065 Fix arrows for JS Tree [SCI-5377]
  app/assets/stylesheets/shared/jstree_override.scss
  vendor/assets/images/32px.png
  vendor/assets/images/40px.png
  vendor/assets/images/throbber.gif
Labels: NextRelease

#3066 Fix error on task page without due date [SCI-5375]
  app/views/my_modules/_due_date_label.html.erb
  app/views/my_modules/_module_header_due_date.html.erb
Labels: NextRelease

#3067 Remove project_folder reference on project archive [SCI-5379]
  app/controllers/projects_controller.rb
Labels: NextRelease

#3070 Add no results page for search on project page [SCI-5333]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/projects.scss
  app/views/projects/index/_team_projects_grouped_by_folder.html.erb
  config/locales/en.yml
  public/images/no_search_results.png
Labels: NextRelease

#3073 Add permission check for open manage user modal button and experiment actions [SCI-5382]
  app/views/projects/index/_project_card.html.erb
  app/views/projects/show/_experiment.html.erb
Labels: NextRelease

#3074 Fix projects page member filter [SCI-5385]
  app/services/projects_overview_service.rb
Labels: NextRelease

#3076 Change button style again [SCI-5335]
  app/views/projects/index/_toolbar.html.erb
Labels: NextRelease

#3062 Add fallback archived_on and archived_by for MyModule and Experiment [SCI-5362]
  app/helpers/experiments_helper.rb
  app/helpers/my_modules_helper.rb
  app/views/canvas/full_zoom/_my_module.html.erb
  app/views/projects/show/_experiment.html.erb
  spec/factories/experiments.rb
  spec/factories/projects.rb
Labels: NextRelease

#3079 Add ProjectFolders relation to Folder Serializer [SCI-5376]
  app/serializers/api/v1/project_folder_serializer.rb
  spec/support/api/schemas/project_folders/item.json
Labels: NextRelease

#3080 Fix border radius [SCI-5388]
  app/assets/stylesheets/shared/jstree_override.scss
Labels: NextRelease

#3085 Small projects pages fixes [SCI-5330]
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/projects/index.html.erb
  app/views/projects/index/_header.html.erb
  config/locales/en.yml
Labels: NextRelease

#3084 Fix comments red dot and ordering of comments [SCI-5384]
  app/controllers/comments_controller.rb
  app/views/projects/index/_folder_card.html.erb
  app/views/shared/comments/_comments_list.html.erb
Labels: NextRelease

#3083 Trigger search on filters flyout close, fix render when filters are clear [SCI-5393]
  app/assets/javascripts/projects/index.js
Labels: NextRelease

#3087 Fix folder's activities links [SCI-5397]
  app/helpers/global_activities_helper.rb
  app/views/global_activities/references/_project_folder.html.erb
Labels: NextRelease

#3086 Fix missing results of archived task [SCI-5394]
  app/controllers/my_modules_controller.rb
Labels: NextRelease

#3068 Fix new project modal initialization [SCI-5381]
  app/assets/javascripts/projects/index.js
Labels: NextRelease

#3088 Fix breadcrumbs order for folders [SCI-5395]
  app/helpers/project_folders_helper.rb
  app/views/projects/index/_breadcrumbs.html.erb
Labels: NextRelease

#3091 Fix archived experiment dropdown and archived view for projects page [SCI-5392]
  app/assets/javascripts/projects/index.js
  app/permissions/experiment.rb
  app/views/projects/index/_header.html.erb
  app/views/projects/show/_experiment.html.erb
Labels: NextRelease

#3092 Fix error message for name in EditProject modal [SCI-5406]
  app/assets/javascripts/projects/index.js
Labels: NextRelease

#3095 Fix red dot icon for projects filters [SCI-5420]
  app/assets/stylesheets/projects.scss
Labels: NextRelease

#3098 Add initialization for select all checkbox in projects table [SCI-5409]
  app/assets/javascripts/projects/index.js
Labels: NextRelease

#3096 Fix edit button for folder in archive mode [SCI-5418]
  app/views/projects/index/_folder_card.html.erb
  app/views/projects/index/_toolbar.html.erb
  config/routes.rb
Labels: NextRelease

#3104 Fix result deletion [SCI-5429]
  app/controllers/results_controller.rb
  app/permissions/result.rb
  app/views/my_modules/archive/_result.html.erb
  spec/controllers/results_controller_spec.rb
  spec/factories/results.rb
Labels: NextRelease

#3109 Fix css for no results on projects page [SCI-5438]
  app/assets/stylesheets/projects.scss
Labels: NextRelease

#3117 Fix report generation [SCI-5446]
  app/assets/stylesheets/shared/jstree_override.scss
Labels: NextRelease

#3111 Add hover effect to project table [SCI-5372]
  app/assets/stylesheets/projects.scss
  app/views/projects/index/_folder_card.html.erb
  app/views/projects/index/_project_card.html.erb
Labels: features/experiments-layout

#3108 Add sticky toolbar for projects page [SCI-5401]
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/repositories.scss
  app/assets/stylesheets/shared/content_pane.scss
  app/views/projects/index.html.erb
  app/views/projects/index/_header.html.erb
  app/views/projects/show/_header.html.erb
  app/views/repositories/index.html.erb
  app/views/repositories/show.html.erb
  app/views/users/registrations/edit.html.erb
Labels: features/experiments-layout

#3118 Add breadcrumbs to project experiments page [SCI-5369]
  app/assets/stylesheets/shared/jstree_override.scss
  app/controllers/projects_controller.rb
  app/views/projects/experiment_archive.html.erb
  app/views/projects/index/_breadcrumbs.html.erb
  app/views/projects/show.html.erb
Labels: features/experiments-layout

#3125 Update Experiments page layout and the toolbar row [SCI-5364]
  app/assets/javascripts/projects/index.js
  app/assets/stylesheets/experiments.scss
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/shared/cards.scss
  app/assets/stylesheets/shared/content_pane.scss
  app/assets/stylesheets/themes/scinote.scss
  app/views/projects/experiment_archive.html.erb
  app/views/projects/index/_header.html.erb
  app/views/projects/index/_toolbar.html.erb
  app/views/projects/show.html.erb
  app/views/projects/show/_experiment_card.html.erb
  app/views/projects/show/_header.html.erb
  app/views/projects/show/_toolbar.html.erb
  app/views/shared/_view_switch.html.erb
  config/locales/en.yml
Labels: features/experiments-layout

#3119 Add filters to experiments pages [SCI-5366]
  app/assets/javascripts/projects/index.js
  app/assets/javascripts/projects/show.js
  app/assets/javascripts/sitewide/filter_dropdown.js
  app/assets/stylesheets/projects.scss
  app/assets/stylesheets/shared/content_pane.scss
  app/assets/stylesheets/shared/filter_dropdown.scss
  app/views/projects/index/_header.html.erb
  app/views/projects/show/_header.html.erb
  app/views/shared/_filter_dropdown.html.erb
  app/views/shared/filter_dropdown/_datetime_search.html.erb
  app/views/shared/filter_dropdown/_text_search.html.erb
  config/locales/en.yml
Labels: features/experiments-layout
